// Code generated by tools/protocolgen. DO NOT EDIT.

export type AgentKind = "claude" | "codex";

export type AstralEvent = {
  seq: number;
  ts: string;
  workspace_id: string;
  session_id: string;
  agent: "claude" | "codex";
  kind: string;
  normalized: unknown;
  raw?: unknown;
};

export type AttachmentIngestChunkParams = {
  session_id: string;
  upload_id: string;
  seq: number;
  offset: number;
  data_base64: string;
};

export type AttachmentIngestChunkResult = {
  session_id: string;
  upload_id: string;
  seq: number;
  offset: number;
  received_bytes: number;
};

export type AttachmentIngestFinishParams = {
  session_id: string;
  upload_id: string;
};

export type AttachmentIngestFinishResult = {
  session_id: string;
  upload_id: string;
  attachment: ControlAttachmentHandle;
};

export type AttachmentIngestParams = {
  session_id: string;
  name: string;
  kind: string;
  mime_type: string;
  detail: string;
  content_base64: string;
};

export type AttachmentIngestResult = {
  session_id: string;
  attachment: ControlAttachmentHandle;
};

export type AttachmentIngestStartParams = {
  session_id: string;
  name: string;
  kind: string;
  mime_type: string;
  detail: string;
  size?: number;
  sha256?: string;
};

export type AttachmentIngestStartResult = {
  session_id: string;
  upload_id: string;
  attachment_id: string;
  chunk_max_bytes: number;
  max_bytes: number;
};

export type ControlAttachmentHandle = {
  id: string;
  media_id: string;
  kind: string;
  name: string;
  mime_type?: string;
  size?: number;
  detail?: string;
  host_owned: boolean;
};

export type EditLastUserMessageRequest = {
  event_seq: number;
  input: string;
  model: string;
  reasoning_effort: string;
  permission_mode: string;
};

export type EditableUserMessageView = {
  event_seq: number;
  text: string;
};

export type ForkSessionRequest = {
  event_seq: number;
};

export type ForkSessionResponse = {
  session: Session;
};

export type InputAttachment = {
  id: string;
  kind: string;
  path: string;
  name: string;
  mime_type?: string;
  size?: number;
  detail?: string;
};

export type InteractionActionView = {
  id: string;
  label: string;
  description?: string;
  role?: string;
  requires_feedback?: boolean;
};

export type InteractionDetailRow = {
  key?: string;
  label: string;
  value: string;
  mono?: boolean;
};

export type MediaReadParams = {
  session_id: string;
  event_seq: number;
  media_id: string;
};

export type MediaReadResult = {
  session_id: string;
  event_seq: number;
  media_id: string;
  kind: string;
  name: string;
  mime_type?: string;
  size?: number;
  content_base64: string;
  download?: boolean;
};

export type MediaStreamCancelParams = {
  stream_id: string;
};

export type MediaStreamCancelResult = {
  stream_id: string;
  cancelled: boolean;
};

export type MediaStreamFrame = {
  stream_id: string;
  resume_token?: string;
  request_id?: string;
  session_id: string;
  event_seq: number;
  media_id: string;
  kind?: string;
  name?: string;
  mime_type?: string;
  size?: number;
  seq: number;
  offset: number;
  data_base64?: string;
  final?: boolean;
  error_code?: string;
  error_message?: string;
};

export type MediaStreamParams = {
  session_id?: string;
  event_seq?: number;
  media_id?: string;
  resume_token?: string;
  offset?: number;
  chunk_size?: number;
};

export type MediaStreamResult = {
  stream_id: string;
  resume_token: string;
  session_id: string;
  event_seq: number;
  media_id: string;
  kind: string;
  name: string;
  mime_type?: string;
  size?: number;
  offset: number;
  chunk_size: number;
};

export type PendingInteractionView = {
  id: string;
  kind: string;
  title: string;
  detail_rows?: InteractionDetailRow[];
  actions: InteractionActionView[];
  form?: Record<string, unknown>;
};

export type QueueControlParams = {
  session_id: string;
  queue_id: string;
};

export type QueuedInputView = {
  id: string;
  session_id: string;
  text: string;
};

export type SSHConfig = {
  endpoint: string;
  port: number;
  remote_cwd: string;
};

export type Session = {
  id: string;
  workspace_id: string;
  agent: "claude" | "codex";
  title?: string;
  status: string;
  native_session_id?: string;
  native_thread_id?: string;
  forked_from_session_id?: string;
  forked_from_event_seq?: number;
  forked_from_native_anchor?: string;
  forked_from_title?: string;
  created_at: string;
  updated_at: string;
};

export type SessionCommand = {
  id: string;
  title: string;
  description?: string;
  icon?: string;
  kind: string;
  enabled: boolean;
  disabled_reason?: string;
  agent?: "claude" | "codex";
  client_action?: string;
  payload?: Record<string, unknown>;
};

export type SessionCommandKind = "action" | "client" | "prompt";

export type SessionCommandListResponse = {
  commands: SessionCommand[];
};

export type SessionCommandRequest = {
  args?: Record<string, unknown>;
};

export type SessionCommandResponse = {
  ok: boolean;
  queued?: boolean;
  queue_id?: string;
};

export type SessionDeleteParams = {
  session_id: string;
};

export type SessionDeleteResult = {
  ok: boolean;
  session_id: string;
};

export type SessionForkControlParams = {
  session_id: string;
  event_seq: number;
};

export type SessionStatus = "failed" | "idle" | "reconnecting" | "requires_action" | "running";

export type SessionView = {
  session: Session;
  title?: string;
  status: string;
  pending_interaction?: PendingInteractionView;
  queued_inputs?: QueuedInputView[];
  editable_user_message?: EditableUserMessageView;
};

export type TerminalAckResult = {
  terminal_id: string;
  status: string;
  output_seq: number;
  writer_device_id?: string;
  can_input?: boolean;
};

export type TerminalAttachParams = {
  terminal_id: string;
  after_seq?: number;
};

export type TerminalAttachResult = {
  terminal_id: string;
  workspace_id: string;
  target: string;
  status: string;
  viewer_device_id: string;
  viewer_id: string;
  input_lease_id: string;
  connection_id: string;
  writer_device_id?: string;
  output_seq: number;
  can_input: boolean;
};

export type TerminalCloseParams = {
  terminal_id: string;
};

export type TerminalDetachParams = {
  terminal_id: string;
};

export type TerminalHeartbeatAckParams = {
  terminal_id: string;
  viewer_id: string;
  input_lease_id: string;
  heartbeat_seq: number;
  rendered_seq?: number;
};

export type TerminalInputParams = {
  terminal_id: string;
  viewer_id?: string;
  input_lease_id?: string;
  data?: string;
};

export type TerminalOpenParams = {
  workspace_id: string;
  cwd?: string;
  cols?: number;
  rows?: number;
};

export type TerminalOpenResult = {
  terminal_id: string;
  workspace_id: string;
  target: string;
  shell?: string;
  cwd?: string;
  status: string;
  writer_device_id?: string;
  output_seq: number;
};

export type TerminalResizeParams = {
  terminal_id: string;
  viewer_id?: string;
  input_lease_id?: string;
  cols: number;
  rows: number;
};

export type TerminalTab = {
  terminal_id: string;
  workspace_id: string;
  agent: string;
  target: string;
  shell?: string;
  cwd?: string;
  status: string;
  writer_device_id?: string;
  output_seq: number;
  created_at: string;
  updated_at: string;
};

export type Workspace = {
  id: string;
  name: string;
  target: string;
  agent: "claude" | "codex";
  local_projection_root: string;
  local_cwd?: string;
  ssh?: SSHConfig;
  native_session_id?: string;
  native_thread_id?: string;
  created_at?: string;
  updated_at?: string;
};

export type WorkspaceConnection = {
  workspace_id: string;
  target: string;
  status: string;
  endpoint?: string;
  port?: number;
  remote_cwd?: string;
  remote_user?: string;
  remote_host?: string;
  remote_os?: string;
  remote_arch?: string;
  remote_shell?: string;
  display_cwd?: string;
  helper_path?: string;
  helper_status?: string;
  capabilities?: Record<string, unknown>;
  message?: string;
  retry_attempt?: number;
  retry_max?: number;
  updated_at: string;
  raw?: Record<string, unknown>;
};

export type WorkspaceExecParams = {
  workspace_id: string;
  command: string;
  cwd: string;
  timeout_ms: number;
};

export type WorkspaceExecResult = {
  workspace_id: string;
  target: string;
  command: string;
  cwd: string;
  approval_policy: string;
  exit_code: number;
  stdout: string;
  stderr: string;
  output?: string;
  stdout_truncated?: boolean;
  stderr_truncated?: boolean;
  output_truncated?: boolean;
  output_bytes_limit?: number;
  duration_ms: number;
  failure?: string;
};

export type WorkspaceFileEntry = {
  name: string;
  path: string;
  kind: string;
  size?: number;
  mod_time?: string;
};

export type WorkspaceFileStreamCancelParams = {
  stream_id: string;
};

export type WorkspaceFileStreamCancelResult = {
  stream_id: string;
  cancelled: boolean;
};

export type WorkspaceFileStreamFrame = {
  stream_id: string;
  request_id?: string;
  workspace_id: string;
  target: string;
  path: string;
  kind?: string;
  name?: string;
  mime_type?: string;
  size?: number;
  seq: number;
  offset: number;
  data_base64?: string;
  final?: boolean;
  error_code?: string;
  error_message?: string;
};

export type WorkspaceFileStreamResult = {
  stream_id: string;
  workspace_id: string;
  target: string;
  path: string;
  kind: string;
  name?: string;
  mime_type?: string;
  size?: number;
  offset: number;
  chunk_size: number;
};

export type WorkspaceFileTextEdit = {
  old_string: string;
  new_string: string;
  replace_all?: boolean;
};

export type WorkspaceFilesApplyPatchParams = {
  workspace_id: string;
  path: string;
  edits: WorkspaceFileTextEdit[];
};

export type WorkspaceFilesApplyPatchResult = {
  workspace_id: string;
  target: string;
  path: string;
  kind: string;
  size: number;
  applied_edits: number;
  structured_patch?: Record<string, unknown>[];
};

export type WorkspaceFilesDeleteParams = {
  workspace_id: string;
  path: string;
  recursive?: boolean;
  force?: boolean;
};

export type WorkspaceFilesDeleteResult = {
  workspace_id: string;
  target: string;
  path: string;
  kind: string;
  removed: boolean;
};

export type WorkspaceFilesMoveParams = {
  workspace_id: string;
  path: string;
  destination_path: string;
  overwrite?: boolean;
  create_parents?: boolean;
};

export type WorkspaceFilesMoveResult = {
  workspace_id: string;
  target: string;
  from_path: string;
  to_path: string;
  kind: string;
  size?: number;
};

export type WorkspaceFilesReadParams = {
  workspace_id: string;
  path: string;
  mode: string;
  max_bytes: number;
};

export type WorkspaceFilesReadResult = {
  workspace_id: string;
  target: string;
  path: string;
  kind: string;
  name?: string;
  size?: number;
  mod_time?: string;
  mime_type?: string;
  content_base64?: string;
  entries?: WorkspaceFileEntry[];
  truncated?: boolean;
};

export type WorkspaceFilesStreamParams = {
  workspace_id: string;
  path: string;
  offset?: number;
  chunk_size?: number;
};

export type WorkspaceFilesWriteParams = {
  workspace_id: string;
  path: string;
  content: string;
  content_base64: string;
  create_parents?: boolean;
};

export type WorkspaceFilesWriteResult = {
  workspace_id: string;
  target: string;
  path: string;
  kind: string;
  size: number;
};

export type WorkspaceReferenceParams = {
  workspace_id: string;
};

export type WorkspaceTarget = "local" | "ssh";

