// Code generated by tools/protocolgen. DO NOT EDIT.

export type ActionError = {
  status: number;
  code: "capability_denied" | "capability_mismatch" | "control_action_unknown" | "control_authorization_required" | "controller_device_required" | "host_service_unavailable" | "invalid_params" | "remote_host_required";
  message: string;
  details: Record<string, string>;
};

export type AgentInfo = {
  path?: string;
  version?: string;
  available: boolean;
  current_model?: string;
  current_effort?: string;
  models?: ModelInfo[];
};

export type AgentKind = "claude" | "codex";

export type ApprovalRequestedNormalized = {
  "additional_permissions"?: unknown;
  "approval_id"?: unknown;
  "available_decisions"?: unknown;
  "changes"?: unknown;
  "command"?: unknown;
  "command_actions"?: unknown;
  "cwd"?: unknown;
  "decision"?: unknown;
  "diff"?: unknown;
  "item_id"?: unknown;
  "kind"?: unknown;
  "network_approval_context"?: unknown;
  "options"?: unknown;
  "params"?: unknown;
  "path"?: unknown;
  "plan"?: unknown;
  "proposed_execpolicy_amendment"?: unknown;
  "proposed_network_amendments"?: unknown;
  "question"?: unknown;
  "reason"?: unknown;
  "request_id"?: unknown;
  "source"?: unknown;
  "text"?: unknown;
  "tool_input"?: unknown;
  "tool_name"?: unknown;
  "turn_id"?: unknown;
  [key: string]: unknown;
};

export type ApprovalResolvedNormalized = {
  "approval_id"?: unknown;
  "decision"?: unknown;
  "request_id"?: unknown;
  "response"?: unknown;
  "source"?: unknown;
  [key: string]: unknown;
};

export type ApprovalRespondedNormalized = {
  "approval_id"?: unknown;
  "decision"?: unknown;
  "request_id"?: unknown;
  "response"?: unknown;
  "source"?: unknown;
  [key: string]: unknown;
};

export type AskRequestedNormalized = {
  "allowCustom"?: unknown;
  "allow_custom"?: unknown;
  "ask_id"?: unknown;
  "fields"?: unknown;
  "isSecret"?: unknown;
  "is_secret"?: unknown;
  "item_id"?: unknown;
  "kind"?: unknown;
  "mode"?: unknown;
  "multiSelect"?: unknown;
  "multi_select"?: unknown;
  "options"?: unknown;
  "params"?: unknown;
  "prompt"?: unknown;
  "question"?: unknown;
  "request_id"?: unknown;
  "requestedSchema"?: unknown;
  "requested_schema"?: unknown;
  "schema"?: unknown;
  "source"?: unknown;
  "text"?: unknown;
  "turn_id"?: unknown;
  "url"?: unknown;
  [key: string]: unknown;
};

export type AskResolvedNormalized = {
  "answers"?: unknown;
  "ask_id"?: unknown;
  "request_id"?: unknown;
  "response"?: unknown;
  "source"?: unknown;
  [key: string]: unknown;
};

export type AstralEventBase = {
  seq: number;
  ts: string;
  workspace_id: string;
  session_id: string;
  agent: AgentKind;
  raw?: unknown;
};

export type AstralEvent =
  | (AstralEventBase & { kind: "approval.requested"; normalized: ApprovalRequestedNormalized })
  | (AstralEventBase & { kind: "approval.resolved"; normalized: ApprovalResolvedNormalized })
  | (AstralEventBase & { kind: "approval.responded"; normalized: ApprovalRespondedNormalized })
  | (AstralEventBase & { kind: "ask.requested"; normalized: AskRequestedNormalized })
  | (AstralEventBase & { kind: "ask.resolved"; normalized: AskResolvedNormalized })
  | (AstralEventBase & { kind: "control.context"; normalized: ControlContextNormalized })
  | (AstralEventBase & { kind: "control.error"; normalized: ControlErrorNormalized })
  | (AstralEventBase & { kind: "control.interrupt"; normalized: ControlInterruptNormalized })
  | (AstralEventBase & { kind: "control.model"; normalized: ControlModelNormalized })
  | (AstralEventBase & { kind: "control.notification"; normalized: ControlNotificationNormalized })
  | (AstralEventBase & { kind: "control.pairing.approved"; normalized: ControlPairingApprovedNormalized })
  | (AstralEventBase & { kind: "control.pairing.denied"; normalized: ControlPairingDeniedNormalized })
  | (AstralEventBase & { kind: "control.pairing.requested"; normalized: ControlPairingRequestedNormalized })
  | (AstralEventBase & { kind: "control.rate_limit"; normalized: ControlRateLimitNormalized })
  | (AstralEventBase & { kind: "control.raw"; normalized: ControlRawNormalized })
  | (AstralEventBase & { kind: "control.status"; normalized: ControlStatusNormalized })
  | (AstralEventBase & { kind: "control.steer"; normalized: ControlSteerNormalized })
  | (AstralEventBase & { kind: "control.terminal.attached"; normalized: ControlTerminalAttachedNormalized })
  | (AstralEventBase & { kind: "control.terminal.closed"; normalized: ControlTerminalClosedNormalized })
  | (AstralEventBase & { kind: "control.terminal.detached"; normalized: ControlTerminalDetachedNormalized })
  | (AstralEventBase & { kind: "control.terminal.opened"; normalized: ControlTerminalOpenedNormalized })
  | (AstralEventBase & { kind: "control.trust.granted"; normalized: ControlTrustGrantedNormalized })
  | (AstralEventBase & { kind: "control.trust.revoked"; normalized: ControlTrustRevokedNormalized })
  | (AstralEventBase & { kind: "control.warning"; normalized: ControlWarningNormalized })
  | (AstralEventBase & { kind: "hook.completed"; normalized: HookCompletedNormalized })
  | (AstralEventBase & { kind: "hook.progress"; normalized: HookProgressNormalized })
  | (AstralEventBase & { kind: "hook.started"; normalized: HookStartedNormalized })
  | (AstralEventBase & { kind: "memory.compacted"; normalized: MemoryCompactedNormalized })
  | (AstralEventBase & { kind: "memory.compacting"; normalized: MemoryCompactingNormalized })
  | (AstralEventBase & { kind: "message.assistant"; normalized: MessageAssistantNormalized })
  | (AstralEventBase & { kind: "message.delta"; normalized: MessageDeltaNormalized })
  | (AstralEventBase & { kind: "message.media"; normalized: MessageMediaNormalized })
  | (AstralEventBase & { kind: "message.started"; normalized: MessageStartedNormalized })
  | (AstralEventBase & { kind: "message.user"; normalized: MessageUserNormalized })
  | (AstralEventBase & { kind: "plan.delta"; normalized: PlanDeltaNormalized })
  | (AstralEventBase & { kind: "plan.updated"; normalized: PlanUpdatedNormalized })
  | (AstralEventBase & { kind: "queue.cancelled"; normalized: QueueCancelledNormalized })
  | (AstralEventBase & { kind: "queue.dequeued"; normalized: QueueDequeuedNormalized })
  | (AstralEventBase & { kind: "queue.failed"; normalized: QueueFailedNormalized })
  | (AstralEventBase & { kind: "queue.queued"; normalized: QueueQueuedNormalized })
  | (AstralEventBase & { kind: "queue.steered"; normalized: QueueSteeredNormalized })
  | (AstralEventBase & { kind: "reasoning.completed"; normalized: ReasoningCompletedNormalized })
  | (AstralEventBase & { kind: "reasoning.delta"; normalized: ReasoningDeltaNormalized })
  | (AstralEventBase & { kind: "reasoning.started"; normalized: ReasoningStartedNormalized })
  | (AstralEventBase & { kind: "session.deleted"; normalized: SessionDeletedNormalized })
  | (AstralEventBase & { kind: "session.native"; normalized: SessionNativeNormalized })
  | (AstralEventBase & { kind: "session.started"; normalized: SessionStartedNormalized })
  | (AstralEventBase & { kind: "session.updated"; normalized: SessionUpdatedNormalized })
  | (AstralEventBase & { kind: "tool.completed"; normalized: ToolCompletedNormalized })
  | (AstralEventBase & { kind: "tool.diff"; normalized: ToolDiffNormalized })
  | (AstralEventBase & { kind: "tool.output_delta"; normalized: ToolOutputDeltaNormalized })
  | (AstralEventBase & { kind: "tool.progress"; normalized: ToolProgressNormalized })
  | (AstralEventBase & { kind: "tool.started"; normalized: ToolStartedNormalized })
  | (AstralEventBase & { kind: "tool.todo"; normalized: ToolTodoNormalized })
  | (AstralEventBase & { kind: "turn.cancelled"; normalized: TurnCancelledNormalized })
  | (AstralEventBase & { kind: "turn.completed"; normalized: TurnCompletedNormalized })
  | (AstralEventBase & { kind: "turn.failed"; normalized: TurnFailedNormalized })
  | (AstralEventBase & { kind: "turn.replaced"; normalized: TurnReplacedNormalized })
  | (AstralEventBase & { kind: "turn.started"; normalized: TurnStartedNormalized })
  | (AstralEventBase & { kind: "workspace.connection"; normalized: WorkspaceConnectionNormalized })
  | (AstralEventBase & { kind: "workspace.created"; normalized: WorkspaceCreatedNormalized })
  | (AstralEventBase & { kind: "workspace.removed"; normalized: WorkspaceRemovedNormalized })
;

export type AstralEventFamily = "approval" | "ask" | "control" | "hook" | "memory" | "message" | "plan" | "queue" | "reasoning" | "session" | "subagent" | "tool" | "turn" | "workspace";

export type AstralEventKind = "approval.requested" | "approval.resolved" | "approval.responded" | "ask.requested" | "ask.resolved" | "control.context" | "control.error" | "control.interrupt" | "control.model" | "control.notification" | "control.pairing.approved" | "control.pairing.denied" | "control.pairing.requested" | "control.rate_limit" | "control.raw" | "control.status" | "control.steer" | "control.terminal.attached" | "control.terminal.closed" | "control.terminal.detached" | "control.terminal.opened" | "control.trust.granted" | "control.trust.revoked" | "control.warning" | "hook.completed" | "hook.progress" | "hook.started" | "memory.compacted" | "memory.compacting" | "message.assistant" | "message.delta" | "message.media" | "message.started" | "message.user" | "plan.delta" | "plan.updated" | "queue.cancelled" | "queue.dequeued" | "queue.failed" | "queue.queued" | "queue.steered" | "reasoning.completed" | "reasoning.delta" | "reasoning.started" | "session.deleted" | "session.native" | "session.started" | "session.updated" | "tool.completed" | "tool.diff" | "tool.output_delta" | "tool.progress" | "tool.started" | "tool.todo" | "turn.cancelled" | "turn.completed" | "turn.failed" | "turn.replaced" | "turn.started" | "workspace.connection" | "workspace.created" | "workspace.removed";

export type AstralEventNormalized = ApprovalRequestedNormalized | ApprovalResolvedNormalized | ApprovalRespondedNormalized | AskRequestedNormalized | AskResolvedNormalized | ControlContextNormalized | ControlErrorNormalized | ControlInterruptNormalized | ControlModelNormalized | ControlNotificationNormalized | ControlPairingApprovedNormalized | ControlPairingDeniedNormalized | ControlPairingRequestedNormalized | ControlRateLimitNormalized | ControlRawNormalized | ControlStatusNormalized | ControlSteerNormalized | ControlTerminalAttachedNormalized | ControlTerminalClosedNormalized | ControlTerminalDetachedNormalized | ControlTerminalOpenedNormalized | ControlTrustGrantedNormalized | ControlTrustRevokedNormalized | ControlWarningNormalized | HookCompletedNormalized | HookProgressNormalized | HookStartedNormalized | MemoryCompactedNormalized | MemoryCompactingNormalized | MessageAssistantNormalized | MessageDeltaNormalized | MessageMediaNormalized | MessageStartedNormalized | MessageUserNormalized | PlanDeltaNormalized | PlanUpdatedNormalized | QueueCancelledNormalized | QueueDequeuedNormalized | QueueFailedNormalized | QueueQueuedNormalized | QueueSteeredNormalized | ReasoningCompletedNormalized | ReasoningDeltaNormalized | ReasoningStartedNormalized | SessionDeletedNormalized | SessionNativeNormalized | SessionStartedNormalized | SessionUpdatedNormalized | ToolCompletedNormalized | ToolDiffNormalized | ToolOutputDeltaNormalized | ToolProgressNormalized | ToolStartedNormalized | ToolTodoNormalized | TurnCancelledNormalized | TurnCompletedNormalized | TurnFailedNormalized | TurnReplacedNormalized | TurnStartedNormalized | WorkspaceConnectionNormalized | WorkspaceCreatedNormalized | WorkspaceRemovedNormalized;

export type AstralEventNormalizedFieldSpec = {
  name: string;
};

export type AttachmentIngestChunkParams = {
  session_id: string;
  upload_id: string;
  seq: number;
  offset: number;
  data_base64: string;
};

export type AttachmentIngestChunkResult = {
  session_id: string;
  upload_id: string;
  seq: number;
  offset: number;
  received_bytes: number;
};

export type AttachmentIngestFinishParams = {
  session_id: string;
  upload_id: string;
};

export type AttachmentIngestFinishResult = {
  session_id: string;
  upload_id: string;
  attachment: ControlAttachmentHandle;
};

export type AttachmentIngestParams = {
  session_id: string;
  name: string;
  kind: string;
  mime_type: string;
  detail: string;
  content_base64: string;
};

export type AttachmentIngestResult = {
  session_id: string;
  attachment: ControlAttachmentHandle;
};

export type AttachmentIngestStartParams = {
  session_id: string;
  name: string;
  kind: string;
  mime_type: string;
  detail: string;
  size?: number;
  sha256?: string;
};

export type AttachmentIngestStartResult = {
  session_id: string;
  upload_id: string;
  attachment_id: string;
  chunk_max_bytes: number;
  max_bytes: number;
};

export type ControlAction = "attachment.ingest" | "attachment.ingest.chunk" | "attachment.ingest.finish" | "attachment.ingest.start" | "core.control.interrupt" | "core.control.native_session.import" | "core.control.queue.cancel" | "core.control.queue.steer" | "core.control.session.create" | "core.control.session.delete" | "core.control.session.fork" | "core.control.session_input" | "core.control.workspace.connect" | "core.control.workspace.create" | "core.control.workspace.delete" | "core.control.workspace.disconnect" | "core.read.events" | "core.read.host_snapshot" | "core.read.native_sessions" | "core.read.ping" | "core.read.session_view" | "core.read.sessions" | "core.read.workbench" | "core.read.workspace.connection" | "core.read.workspaces" | "core.subscribe.events" | "core.unsubscribe.events" | "host.fs.browse" | "host.pairing.approve" | "host.pairing.deny" | "host.pairing.list" | "host.trust.list" | "host.trust.revoke" | "interaction.respond" | "media.download" | "media.read" | "media.stream" | "media.stream.cancel" | "session.edit" | "terminal.attach" | "terminal.close" | "terminal.detach" | "terminal.heartbeat_ack" | "terminal.input" | "terminal.list" | "terminal.open" | "terminal.resize" | "workspace.exec" | "workspace.files.apply_patch" | "workspace.files.delete" | "workspace.files.move" | "workspace.files.read" | "workspace.files.stream" | "workspace.files.stream.cancel" | "workspace.files.write";

export type ControlActionSpec = {
  action: "attachment.ingest" | "attachment.ingest.chunk" | "attachment.ingest.finish" | "attachment.ingest.start" | "core.control.interrupt" | "core.control.native_session.import" | "core.control.queue.cancel" | "core.control.queue.steer" | "core.control.session.create" | "core.control.session.delete" | "core.control.session.fork" | "core.control.session_input" | "core.control.workspace.connect" | "core.control.workspace.create" | "core.control.workspace.delete" | "core.control.workspace.disconnect" | "core.read.events" | "core.read.host_snapshot" | "core.read.native_sessions" | "core.read.ping" | "core.read.session_view" | "core.read.sessions" | "core.read.workbench" | "core.read.workspace.connection" | "core.read.workspaces" | "core.subscribe.events" | "core.unsubscribe.events" | "host.fs.browse" | "host.pairing.approve" | "host.pairing.deny" | "host.pairing.list" | "host.trust.list" | "host.trust.revoke" | "interaction.respond" | "media.download" | "media.read" | "media.stream" | "media.stream.cancel" | "session.edit" | "terminal.attach" | "terminal.close" | "terminal.detach" | "terminal.heartbeat_ack" | "terminal.input" | "terminal.list" | "terminal.open" | "terminal.resize" | "workspace.exec" | "workspace.files.apply_patch" | "workspace.files.delete" | "workspace.files.move" | "workspace.files.read" | "workspace.files.stream" | "workspace.files.stream.cancel" | "workspace.files.write";
  capability: "attachment.ingest" | "core.control" | "core.read" | "host.fs.browse" | "host.manage" | "interaction.respond" | "media.download" | "media.read" | "media.stream" | "session.edit" | "terminal.input" | "terminal.open" | "workspace.exec" | "workspace.files.read" | "workspace.files.write";
  params_type?: string;
  result_type?: string;
};

export type ControlAttachmentHandle = {
  id: string;
  media_id: string;
  kind: string;
  name: string;
  mime_type?: string;
  size?: number;
  detail?: string;
  host_owned: boolean;
};

export type ControlCapability = "attachment.ingest" | "core.control" | "core.read" | "host.fs.browse" | "host.manage" | "interaction.respond" | "media.download" | "media.read" | "media.stream" | "session.edit" | "terminal.input" | "terminal.open" | "workspace.exec" | "workspace.files.read" | "workspace.files.write";

export type ControlContextNormalized = {
  "cache_creation_input_tokens"?: unknown;
  "cached_input_tokens"?: unknown;
  "cumulative_cache_creation_input_tokens"?: unknown;
  "cumulative_cached_input_tokens"?: unknown;
  "cumulative_input_tokens"?: unknown;
  "cumulative_output_tokens"?: unknown;
  "cumulative_total_tokens"?: unknown;
  "input_tokens"?: unknown;
  "model"?: unknown;
  "model_context_window"?: unknown;
  "model_usage"?: unknown;
  "native_session_id"?: unknown;
  "native_thread_id"?: unknown;
  "output_tokens"?: unknown;
  "reasoning_tokens"?: unknown;
  "scope"?: unknown;
  "source"?: unknown;
  "token_usage"?: unknown;
  "total_tokens"?: unknown;
  "usage"?: unknown;
  "used_percent"?: unknown;
  [key: string]: unknown;
};

export type ControlError = {
  status?: number;
  code: "capability_denied" | "capability_mismatch" | "control_action_unknown" | "control_authorization_required" | "controller_device_required" | "host_service_unavailable" | "invalid_params" | "remote_host_required";
  message: string;
  details?: Record<string, string>;
};

export type ControlErrorCode = "capability_denied" | "capability_mismatch" | "control_action_unknown" | "control_authorization_required" | "controller_device_required" | "host_service_unavailable" | "invalid_params" | "remote_host_required";

export type ControlErrorNormalized = {
  "code"?: unknown;
  "details"?: unknown;
  "message"?: unknown;
  "reason"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  [key: string]: unknown;
};

export type ControlInterruptNormalized = {
  "request_id"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  "turn_id"?: unknown;
  [key: string]: unknown;
};

export type ControlModelNormalized = {
  "method"?: unknown;
  "params"?: unknown;
  "source"?: unknown;
  [key: string]: unknown;
};

export type ControlNotificationNormalized = {
  "body"?: unknown;
  "notification_id"?: unknown;
  "reason"?: unknown;
  "source"?: unknown;
  "source_event"?: unknown;
  "target"?: unknown;
  "title"?: unknown;
  "visibility"?: unknown;
  [key: string]: unknown;
};

export type ControlPairingApprovedNormalized = {
  "controller_device_id"?: unknown;
  "host_device_id"?: unknown;
  "request_id"?: unknown;
  "status"?: unknown;
  [key: string]: unknown;
};

export type ControlPairingDeniedNormalized = {
  "controller_device_id"?: unknown;
  "host_device_id"?: unknown;
  "request_id"?: unknown;
  "status"?: unknown;
  [key: string]: unknown;
};

export type ControlPairingRequestedNormalized = {
  "capabilities"?: unknown;
  "cloud_request_id"?: unknown;
  "controller_device_id"?: unknown;
  "controller_device_kind"?: unknown;
  "controller_device_name"?: unknown;
  "controller_public_key_fingerprint"?: unknown;
  "host_device_id"?: unknown;
  "request_id"?: unknown;
  "scope"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  [key: string]: unknown;
};

export type ControlRateLimitNormalized = {
  "limits"?: unknown;
  "source"?: unknown;
  [key: string]: unknown;
};

export type ControlRawNormalized = {
  "error"?: unknown;
  "method"?: unknown;
  "normalized"?: unknown;
  "original_kind"?: unknown;
  "raw"?: unknown;
  "source"?: unknown;
  "subtype"?: unknown;
  "type"?: unknown;
  "value"?: unknown;
  [key: string]: unknown;
};

export type ControlRequest = {
  request_id?: string;
  controller_device_id?: string;
  capability: "attachment.ingest" | "core.control" | "core.read" | "host.fs.browse" | "host.manage" | "interaction.respond" | "media.download" | "media.read" | "media.stream" | "session.edit" | "terminal.input" | "terminal.open" | "workspace.exec" | "workspace.files.read" | "workspace.files.write";
  action: "attachment.ingest" | "attachment.ingest.chunk" | "attachment.ingest.finish" | "attachment.ingest.start" | "core.control.interrupt" | "core.control.native_session.import" | "core.control.queue.cancel" | "core.control.queue.steer" | "core.control.session.create" | "core.control.session.delete" | "core.control.session.fork" | "core.control.session_input" | "core.control.workspace.connect" | "core.control.workspace.create" | "core.control.workspace.delete" | "core.control.workspace.disconnect" | "core.read.events" | "core.read.host_snapshot" | "core.read.native_sessions" | "core.read.ping" | "core.read.session_view" | "core.read.sessions" | "core.read.workbench" | "core.read.workspace.connection" | "core.read.workspaces" | "core.subscribe.events" | "core.unsubscribe.events" | "host.fs.browse" | "host.pairing.approve" | "host.pairing.deny" | "host.pairing.list" | "host.trust.list" | "host.trust.revoke" | "interaction.respond" | "media.download" | "media.read" | "media.stream" | "media.stream.cancel" | "session.edit" | "terminal.attach" | "terminal.close" | "terminal.detach" | "terminal.heartbeat_ack" | "terminal.input" | "terminal.list" | "terminal.open" | "terminal.resize" | "workspace.exec" | "workspace.files.apply_patch" | "workspace.files.delete" | "workspace.files.move" | "workspace.files.read" | "workspace.files.stream" | "workspace.files.stream.cancel" | "workspace.files.write";
  params?: Record<string, unknown>;
};

export type ControlResponse = {
  request_id?: string;
  ok: boolean;
  result?: unknown;
  error?: ControlError;
};

export type ControlStatusNormalized = {
  "active_flags"?: unknown;
  "kind"?: unknown;
  "message"?: unknown;
  "name"?: unknown;
  "permission_mode"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  [key: string]: unknown;
};

export type ControlSteerNormalized = {
  "source"?: unknown;
  "status"?: unknown;
  "turn_id"?: unknown;
  [key: string]: unknown;
};

export type ControlTerminalAttachedNormalized = {
  "input_lease_id"?: unknown;
  "status"?: unknown;
  "terminal_id"?: unknown;
  "viewer_id"?: unknown;
  [key: string]: unknown;
};

export type ControlTerminalClosedNormalized = {
  "reason"?: unknown;
  "status"?: unknown;
  "terminal_id"?: unknown;
  [key: string]: unknown;
};

export type ControlTerminalDetachedNormalized = {
  "reason"?: unknown;
  "released"?: unknown;
  "status"?: unknown;
  "terminal_id"?: unknown;
  "viewer_id"?: unknown;
  [key: string]: unknown;
};

export type ControlTerminalOpenedNormalized = {
  "cwd"?: unknown;
  "shell"?: unknown;
  "status"?: unknown;
  "terminal_id"?: unknown;
  [key: string]: unknown;
};

export type ControlTrustGrantedNormalized = {
  "capabilities"?: unknown;
  "controller_device_id"?: unknown;
  "host_device_id"?: unknown;
  "pairing_request_id"?: unknown;
  "scope"?: unknown;
  [key: string]: unknown;
};

export type ControlTrustRevokedNormalized = {
  "controller_device_id"?: unknown;
  "host_device_id"?: unknown;
  "released_terminal_writers"?: unknown;
  "revoked_at"?: unknown;
  [key: string]: unknown;
};

export type ControlWarningNormalized = {
  "attempt"?: unknown;
  "error"?: unknown;
  "error_status"?: unknown;
  "kind"?: unknown;
  "max_retries"?: unknown;
  "message"?: unknown;
  "name"?: unknown;
  "retry_delay_ms"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  [key: string]: unknown;
};

export type CreateSessionRequest = {
  workspace_id: string;
  agent?: "claude" | "codex";
};

export type CreateWorkspaceRequest = {
  name: string;
  target: string;
  agent?: "claude" | "codex";
  local_cwd?: string;
  ssh?: SSHConfig;
};

export type DeviceIdentity = {
  device_id: string;
  device_name: string;
  device_kind: string;
  public_key: string;
  public_key_fingerprint: string;
  capabilities: "attachment.ingest" | "core.control" | "core.read" | "host.fs.browse" | "host.manage" | "interaction.respond" | "media.download" | "media.read" | "media.stream" | "session.edit" | "terminal.input" | "terminal.open" | "workspace.exec" | "workspace.files.read" | "workspace.files.write"[];
  created_at: string;
  updated_at: string;
};

export type EditLastUserMessageRequest = {
  event_seq: number;
  input: string;
  model: string;
  reasoning_effort: string;
  permission_mode: string;
};

export type EditableUserMessageView = {
  event_seq: number;
  text: string;
};

export type EventSubscriptionCancelParams = {
  stream_id: string;
};

export type EventSubscriptionCancelResult = {
  stream_id: string;
  cancelled: boolean;
};

export type EventSubscriptionParams = {
  workspace_id?: string;
  session_id?: string;
  after_seq?: number;
  replay_limit?: number;
};

export type EventSubscriptionResult = {
  stream_id: string;
  workspace_id?: string;
  session_id?: string;
  after_seq?: number;
  replay_limit?: number;
};

export type EventWindowParams = {
  workspace_id?: string;
  session_id?: string;
  after_seq?: number;
  before_seq?: number;
  limit?: number;
};

export type ForkSessionRequest = {
  event_seq: number;
};

export type ForkSessionResponse = {
  session: Session;
};

export type HookCompletedNormalized = {
  "exit_code"?: unknown;
  "hook_event_name"?: unknown;
  "id"?: unknown;
  "name"?: unknown;
  "outcome"?: unknown;
  "output"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  "stderr"?: unknown;
  "stdout"?: unknown;
  [key: string]: unknown;
};

export type HookProgressNormalized = {
  "exit_code"?: unknown;
  "hook_event_name"?: unknown;
  "id"?: unknown;
  "name"?: unknown;
  "outcome"?: unknown;
  "output"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  "stderr"?: unknown;
  "stdout"?: unknown;
  [key: string]: unknown;
};

export type HookStartedNormalized = {
  "exit_code"?: unknown;
  "hook_event_name"?: unknown;
  "id"?: unknown;
  "name"?: unknown;
  "outcome"?: unknown;
  "output"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  "stderr"?: unknown;
  "stdout"?: unknown;
  [key: string]: unknown;
};

export type HostFileSystemBrowseParams = {
  target: string;
  path?: string;
  ssh?: SSHConfig;
};

export type HostFileSystemBrowseResult = {
  target: string;
  platform: string;
  separator: string;
  path: string;
  parent_path?: string;
  roots: HostFileSystemRoot[];
  entries: HostFileSystemEntry[];
  truncated?: boolean;
};

export type HostFileSystemEntry = {
  name: string;
  path: string;
  kind: string;
  size?: number;
  mod_time?: string;
};

export type HostFileSystemRoot = {
  id: string;
  label: string;
  path: string;
  kind: string;
};

export type HostInfo = {
  identity: DeviceIdentity;
  platform: Record<string, string>;
  features: Record<string, unknown>;
  capabilities: "attachment.ingest" | "core.control" | "core.read" | "host.fs.browse" | "host.manage" | "interaction.respond" | "media.download" | "media.read" | "media.stream" | "session.edit" | "terminal.input" | "terminal.open" | "workspace.exec" | "workspace.files.read" | "workspace.files.write"[];
};

export type HostSnapshotRequest = {
  event_limit?: number;
  restore_on_launch?: boolean;
};

export type HostSnapshotResponse = {
  host: HostInfo;
  agents?: Record<string, unknown>;
  workspaces: Workspace[];
  sessions: Session[];
  workspace_connections?: WorkspaceConnection[];
  events: AstralEvent[];
  session_views: SessionView[];
  initial_session_events?: AstralEvent[];
  workbench?: WorkbenchState;
};

export type HostTrustListResult = {
  grants: TrustGrant[];
};

export type HostTrustRevokeParams = {
  controller_device_id: string;
};

export type HostTrustRevokeResult = {
  controller_device_id: string;
  grant: TrustGrant;
  closed_control_sessions: number;
  released_terminal_writers: number;
  revoked_at?: string;
};

export type InputAttachment = {
  id: string;
  kind: string;
  path: string;
  name: string;
  mime_type?: string;
  size?: number;
  detail?: string;
};

export type InteractionActionView = {
  id: string;
  label: string;
  description?: string;
  role?: string;
  requires_feedback?: boolean;
};

export type InteractionDetailRow = {
  key?: string;
  label: string;
  value: string;
  mono?: boolean;
};

export type InteractionRespondParams = {
  interaction_id: string;
  response: Record<string, unknown>;
};

export type MediaReadParams = {
  session_id: string;
  event_seq: number;
  media_id: string;
};

export type MediaReadResult = {
  session_id: string;
  event_seq: number;
  media_id: string;
  kind: string;
  name: string;
  mime_type?: string;
  size?: number;
  content_base64: string;
  download?: boolean;
};

export type MediaStreamCancelParams = {
  stream_id: string;
};

export type MediaStreamCancelResult = {
  stream_id: string;
  cancelled: boolean;
};

export type MediaStreamFrame = {
  stream_id: string;
  resume_token?: string;
  request_id?: string;
  session_id: string;
  event_seq: number;
  media_id: string;
  kind?: string;
  name?: string;
  mime_type?: string;
  size?: number;
  seq: number;
  offset: number;
  data_base64?: string;
  final?: boolean;
  error_code?: string;
  error_message?: string;
};

export type MediaStreamParams = {
  session_id?: string;
  event_seq?: number;
  media_id?: string;
  resume_token?: string;
  offset?: number;
  chunk_size?: number;
};

export type MediaStreamResult = {
  stream_id: string;
  resume_token: string;
  session_id: string;
  event_seq: number;
  media_id: string;
  kind: string;
  name: string;
  mime_type?: string;
  size?: number;
  offset: number;
  chunk_size: number;
};

export type MemoryCompactedNormalized = {
  "item_id"?: unknown;
  "metadata"?: unknown;
  "source"?: unknown;
  "turn_id"?: unknown;
  [key: string]: unknown;
};

export type MemoryCompactingNormalized = {
  "message"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  [key: string]: unknown;
};

export type MessageAssistantNormalized = {
  "attachments"?: unknown;
  "fork_projection"?: unknown;
  "item_id"?: unknown;
  "media"?: unknown;
  "message_id"?: unknown;
  "native_message_uuid"?: unknown;
  "source"?: unknown;
  "source_seq"?: unknown;
  "source_session_id"?: unknown;
  "suppress_notification"?: unknown;
  "text"?: unknown;
  [key: string]: unknown;
};

export type MessageDeltaNormalized = {
  "item_id"?: unknown;
  "message_id"?: unknown;
  "source"?: unknown;
  "text"?: unknown;
  [key: string]: unknown;
};

export type MessageMediaNormalized = {
  "detail"?: unknown;
  "height"?: unknown;
  "item_id"?: unknown;
  "kind"?: unknown;
  "media_id"?: unknown;
  "mime_type"?: unknown;
  "name"?: unknown;
  "path"?: unknown;
  "revised_prompt"?: unknown;
  "saved_path"?: unknown;
  "size"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  "width"?: unknown;
  [key: string]: unknown;
};

export type MessageStartedNormalized = {
  "item_id"?: unknown;
  "message_id"?: unknown;
  "source"?: unknown;
  [key: string]: unknown;
};

export type MessageUserNormalized = {
  "attachments"?: unknown;
  "fork_projection"?: unknown;
  "input"?: unknown;
  "media"?: unknown;
  "source"?: unknown;
  "source_seq"?: unknown;
  "source_session_id"?: unknown;
  "suppress_notification"?: unknown;
  "text"?: unknown;
  [key: string]: unknown;
};

export type ModelInfo = {
  id: string;
  label?: string;
  source?: string;
  slot?: string;
  default_reasoning_effort?: string;
  supported_reasoning_efforts?: string[];
  context_window?: number;
  max_context_window?: number;
  effective_context_window?: number;
  effective_context_window_percent?: number;
};

export type NativeSessionImportParams = {
  workspace_id: string;
  session_id: string;
};

export type NativeSessionImportResponse = {
  session: Session;
};

export type NativeSessionListResponse = {
  sessions: Session[];
};

export type NativeSessionRef = {
  agent: "claude" | "codex";
  local_path?: string;
  remote_path?: string;
  native_session_id?: string;
  native_thread_id?: string;
  workspace_cwd?: string;
};

export type NativeSessionsReadParams = {
  workspace_id: string;
};

export type OkResult = {
  ok: boolean;
};

export type PairingRequest = {
  request_id: string;
  source?: string;
  cloud_request_id?: string;
  host_device_id: string;
  controller_device_id: string;
  controller_device_name?: string;
  controller_device_kind?: string;
  controller_public_key: string;
  controller_public_key_fingerprint: string;
  scope: string;
  status: string;
  capabilities: string[];
  workspace_exec_policy?: string;
  created_at: string;
  updated_at: string;
  resolved_at?: string;
};

export type PairingRequestListResult = {
  requests: PairingRequest[];
};

export type PairingRequestResolveParams = {
  request_id: string;
};

export type PairingRequestResolveResult = {
  request: PairingRequest;
  grant?: TrustGrant;
};

export type PendingInteractionView = {
  id: string;
  kind: string;
  title: string;
  detail_rows?: InteractionDetailRow[];
  actions: InteractionActionView[];
  form?: Record<string, unknown>;
};

export type PlanDeltaNormalized = {
  "item_id"?: unknown;
  "source"?: unknown;
  "text"?: unknown;
  [key: string]: unknown;
};

export type PlanUpdatedNormalized = {
  "item_id"?: unknown;
  "plan"?: unknown;
  "source"?: unknown;
  "text"?: unknown;
  "turn_id"?: unknown;
  [key: string]: unknown;
};

export type QueueCancelledNormalized = {
  "internal"?: unknown;
  "queue_id"?: unknown;
  "reason"?: unknown;
  "text"?: unknown;
  [key: string]: unknown;
};

export type QueueControlParams = {
  session_id: string;
  queue_id: string;
};

export type QueueControlResult = {
  ok: boolean;
  queue_id: string;
};

export type QueueDequeuedNormalized = {
  "internal"?: unknown;
  "queue_id"?: unknown;
  "text"?: unknown;
  [key: string]: unknown;
};

export type QueueFailedNormalized = {
  "internal"?: unknown;
  "message"?: unknown;
  "queue_id"?: unknown;
  "reason"?: unknown;
  "text"?: unknown;
  [key: string]: unknown;
};

export type QueueQueuedNormalized = {
  "internal"?: unknown;
  "queue_id"?: unknown;
  "session_id"?: unknown;
  "text"?: unknown;
  [key: string]: unknown;
};

export type QueueSteeredNormalized = {
  "internal"?: unknown;
  "queue_id"?: unknown;
  "text"?: unknown;
  [key: string]: unknown;
};

export type QueuedInputView = {
  id: string;
  session_id: string;
  text: string;
};

export type ReasoningCompletedNormalized = {
  "item_id"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  "summary"?: unknown;
  "text"?: unknown;
  [key: string]: unknown;
};

export type ReasoningDeltaNormalized = {
  "item_id"?: unknown;
  "source"?: unknown;
  "text"?: unknown;
  [key: string]: unknown;
};

export type ReasoningStartedNormalized = {
  "item_id"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  "summary"?: unknown;
  "text"?: unknown;
  [key: string]: unknown;
};

export type SSHConfig = {
  endpoint: string;
  port: number;
  remote_cwd: string;
};

export type Session = {
  id: string;
  workspace_id: string;
  agent: "claude" | "codex";
  title?: string;
  status: string;
  source?: "discovered" | "legacy_unlinked" | "linked" | "managed";
  native_ref?: NativeSessionRef;
  managed_by_astralops?: boolean;
  native_session_id?: string;
  native_thread_id?: string;
  forked_from_session_id?: string;
  forked_from_event_seq?: number;
  forked_from_native_anchor?: string;
  forked_from_title?: string;
  created_at: string;
  updated_at: string;
};

export type SessionCommand = {
  id: string;
  title: string;
  description?: string;
  icon?: string;
  kind: string;
  enabled: boolean;
  disabled_reason?: string;
  agent?: "claude" | "codex";
  client_action?: string;
  payload?: Record<string, unknown>;
};

export type SessionCommandKind = "action" | "client" | "prompt";

export type SessionCommandListResponse = {
  commands: SessionCommand[];
};

export type SessionCommandRequest = {
  args?: Record<string, unknown>;
};

export type SessionCommandResponse = {
  ok: boolean;
  queued?: boolean;
  queue_id?: string;
};

export type SessionDeleteParams = {
  session_id: string;
};

export type SessionDeleteResult = {
  ok: boolean;
  session_id: string;
};

export type SessionDeletedNormalized = {
  "message"?: unknown;
  "reason"?: unknown;
  "session_id"?: unknown;
  [key: string]: unknown;
};

export type SessionEditParams = {
  session_id: string;
  event_seq: number;
  input: string;
  model?: string;
  reasoning_effort?: string;
  permission_mode?: string;
};

export type SessionForkControlParams = {
  session_id: string;
  event_seq: number;
};

export type SessionForkResponse = {
  session: Session;
};

export type SessionInputControlParams = {
  session_id: string;
  input: string;
  attachments?: ControlAttachmentHandle[];
  model?: string;
  reasoning_effort?: string;
  permission_mode?: string;
};

export type SessionInputRequest = {
  input: string;
  attachments?: ControlAttachmentHandle[];
  model?: string;
  reasoning_effort?: string;
  permission_mode?: string;
};

export type SessionInputResult = {
  ok: boolean;
  mode: string;
  queued?: boolean;
  steered?: boolean;
  queue_id?: string;
};

export type SessionLinkState = {
  session_id: string;
  workspace_id: string;
  source: "discovered" | "legacy_unlinked" | "linked" | "managed";
  native_ref?: NativeSessionRef;
  managed_by_astralops: boolean;
  created_at: string;
  updated_at: string;
};

export type SessionNativeNormalized = {
  "aiTitle"?: unknown;
  "customTitle"?: unknown;
  "firstPrompt"?: unknown;
  "name"?: unknown;
  "native_session_id"?: unknown;
  "native_thread_id"?: unknown;
  "preview"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  "subtype"?: unknown;
  "summary"?: unknown;
  "title"?: unknown;
  "type"?: unknown;
  [key: string]: unknown;
};

export type SessionReferenceParams = {
  session_id: string;
};

export type SessionSource = "discovered" | "legacy_unlinked" | "linked" | "managed";

export type SessionStartedNormalized = {
  "agent"?: unknown;
  "created_at"?: unknown;
  "forked_from_event_seq"?: unknown;
  "forked_from_session_id"?: unknown;
  "forked_from_title"?: unknown;
  "id"?: unknown;
  "managed_by_astralops"?: unknown;
  "native_ref"?: unknown;
  "native_session_id"?: unknown;
  "native_thread_id"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  "title"?: unknown;
  "updated_at"?: unknown;
  "workspace_id"?: unknown;
  [key: string]: unknown;
};

export type SessionStatus = "failed" | "idle" | "reconnecting" | "requires_action" | "running";

export type SessionUpdatedNormalized = {
  "description"?: unknown;
  "name"?: unknown;
  "recent_action"?: unknown;
  "source"?: unknown;
  "subtype"?: unknown;
  "summarizes_uuid"?: unknown;
  "summary"?: unknown;
  "thread_name"?: unknown;
  "title"?: unknown;
  "type"?: unknown;
  [key: string]: unknown;
};

export type SessionView = {
  session: Session;
  title?: string;
  status: string;
  pending_interaction?: PendingInteractionView;
  queued_inputs?: QueuedInputView[];
  editable_user_message?: EditableUserMessageView;
};

export type SessionsReadParams = {
  workspace_id?: string;
};

export type TerminalAckResult = {
  terminal_id: string;
  status: string;
  output_seq: number;
  writer_device_id?: string;
  can_input?: boolean;
};

export type TerminalAttachParams = {
  terminal_id: string;
  after_seq?: number;
};

export type TerminalAttachResult = {
  terminal_id: string;
  workspace_id: string;
  target: string;
  status: string;
  viewer_device_id: string;
  viewer_id: string;
  input_lease_id: string;
  connection_id: string;
  writer_device_id?: string;
  output_seq: number;
  can_input: boolean;
};

export type TerminalCloseParams = {
  terminal_id: string;
};

export type TerminalDetachParams = {
  terminal_id: string;
};

export type TerminalHeartbeatAckParams = {
  terminal_id: string;
  viewer_id: string;
  input_lease_id: string;
  heartbeat_seq: number;
  rendered_seq?: number;
};

export type TerminalInputParams = {
  terminal_id: string;
  viewer_id?: string;
  input_lease_id?: string;
  data?: string;
};

export type TerminalOpenParams = {
  workspace_id: string;
  cwd?: string;
  cols?: number;
  rows?: number;
};

export type TerminalOpenResult = {
  terminal_id: string;
  workspace_id: string;
  target: string;
  shell?: string;
  cwd?: string;
  status: string;
  writer_device_id?: string;
  output_seq: number;
};

export type TerminalResizeParams = {
  terminal_id: string;
  viewer_id?: string;
  input_lease_id?: string;
  cols: number;
  rows: number;
};

export type TerminalTab = {
  terminal_id: string;
  workspace_id: string;
  agent: string;
  target: string;
  shell?: string;
  cwd?: string;
  status: string;
  writer_device_id?: string;
  output_seq: number;
  created_at: string;
  updated_at: string;
};

export type ToolCompletedNormalized = {
  "category"?: unknown;
  "command"?: unknown;
  "content"?: unknown;
  "cwd"?: unknown;
  "file_path"?: unknown;
  "hidden"?: unknown;
  "id"?: unknown;
  "is_error"?: unknown;
  "item_id"?: unknown;
  "name"?: unknown;
  "path"?: unknown;
  "result"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  "text"?: unknown;
  "visibility"?: unknown;
  [key: string]: unknown;
};

export type ToolDiffNormalized = {
  "diff"?: unknown;
  "item_id"?: unknown;
  "patch"?: unknown;
  "source"?: unknown;
  "turn_id"?: unknown;
  [key: string]: unknown;
};

export type ToolOutputDeltaNormalized = {
  "category"?: unknown;
  "id"?: unknown;
  "item_id"?: unknown;
  "name"?: unknown;
  "source"?: unknown;
  "text"?: unknown;
  [key: string]: unknown;
};

export type ToolProgressNormalized = {
  "category"?: unknown;
  "elapsed_time_seconds"?: unknown;
  "id"?: unknown;
  "name"?: unknown;
  "parent_tool_use_id"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  "task_id"?: unknown;
  "text"?: unknown;
  [key: string]: unknown;
};

export type ToolStartedNormalized = {
  "category"?: unknown;
  "command"?: unknown;
  "cwd"?: unknown;
  "effective_command"?: unknown;
  "id"?: unknown;
  "input"?: unknown;
  "item_id"?: unknown;
  "name"?: unknown;
  "native_command"?: unknown;
  "params"?: unknown;
  "remote_command"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  "text"?: unknown;
  [key: string]: unknown;
};

export type ToolTodoNormalized = {
  "source"?: unknown;
  "text"?: unknown;
  "todos"?: unknown;
  [key: string]: unknown;
};

export type TrustGrant = {
  host_device_id: string;
  controller_device_id: string;
  controller_device_name?: string;
  controller_public_key?: string;
  controller_public_key_fingerprint?: string;
  scope: string;
  status: string;
  capabilities: string[];
  workspace_exec_policy?: string;
  created_at: string;
  updated_at: string;
  revoked_at?: string;
};

export type TurnCancelledNormalized = {
  "reason"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  "turn_id"?: unknown;
  [key: string]: unknown;
};

export type TurnCompletedNormalized = {
  "duration_ms"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  "turn_id"?: unknown;
  [key: string]: unknown;
};

export type TurnFailedNormalized = {
  "message"?: unknown;
  "reason"?: unknown;
  "source"?: unknown;
  "status"?: unknown;
  "turn_id"?: unknown;
  [key: string]: unknown;
};

export type TurnReplacedNormalized = {
  "end_seq"?: unknown;
  "from_seq"?: unknown;
  "replacement_session_id"?: unknown;
  "source"?: unknown;
  "source_session_id"?: unknown;
  "start_seq"?: unknown;
  "status"?: unknown;
  "to_seq"?: unknown;
  [key: string]: unknown;
};

export type TurnStartedNormalized = {
  "source"?: unknown;
  "status"?: unknown;
  "turn_id"?: unknown;
  [key: string]: unknown;
};

export type WorkbenchPanel = {
  id: string;
  kind: string;
  state?: Record<string, unknown>;
  updated_at?: string;
};

export type WorkbenchState = {
  version: number;
  updated_at: string;
  agents?: Record<string, unknown>;
  workspaces: Record<string, Workspace>;
  sessions: Record<string, Session>;
  session_views: Record<string, SessionView>;
  workspace_connections: Record<string, WorkspaceConnection>;
  terminal_tabs: Record<string, TerminalTab>;
  panels: Record<string, WorkbenchPanel>;
};

export type Workspace = {
  id: string;
  name: string;
  target: string;
  agent: "claude" | "codex";
  local_projection_root: string;
  local_cwd?: string;
  ssh?: SSHConfig;
  native_session_id?: string;
  native_thread_id?: string;
  created_at?: string;
  updated_at?: string;
};

export type WorkspaceConnection = {
  workspace_id: string;
  target: string;
  status: string;
  endpoint?: string;
  port?: number;
  remote_cwd?: string;
  remote_user?: string;
  remote_host?: string;
  remote_os?: string;
  remote_arch?: string;
  remote_shell?: string;
  display_cwd?: string;
  helper_path?: string;
  helper_status?: string;
  capabilities?: Record<string, unknown>;
  message?: string;
  retry_attempt?: number;
  retry_max?: number;
  updated_at: string;
  raw?: Record<string, unknown>;
};

export type WorkspaceConnectionNormalized = {
  "capabilities"?: unknown;
  "display_cwd"?: unknown;
  "endpoint"?: unknown;
  "helper_path"?: unknown;
  "helper_status"?: unknown;
  "message"?: unknown;
  "port"?: unknown;
  "remote_arch"?: unknown;
  "remote_cwd"?: unknown;
  "remote_host"?: unknown;
  "remote_os"?: unknown;
  "remote_shell"?: unknown;
  "remote_user"?: unknown;
  "retry_attempt"?: unknown;
  "retry_max"?: unknown;
  "status"?: unknown;
  "target"?: unknown;
  "updated_at"?: unknown;
  "workspace_id"?: unknown;
  [key: string]: unknown;
};

export type WorkspaceCreatedNormalized = {
  "agent"?: unknown;
  "created_at"?: unknown;
  "id"?: unknown;
  "local_cwd"?: unknown;
  "local_projection_root"?: unknown;
  "name"?: unknown;
  "ssh"?: unknown;
  "target"?: unknown;
  "updated_at"?: unknown;
  [key: string]: unknown;
};

export type WorkspaceExecParams = {
  workspace_id: string;
  command: string;
  cwd: string;
  timeout_ms: number;
};

export type WorkspaceExecResult = {
  workspace_id: string;
  target: string;
  command: string;
  cwd: string;
  approval_policy: string;
  exit_code: number;
  stdout: string;
  stderr: string;
  output?: string;
  stdout_truncated?: boolean;
  stderr_truncated?: boolean;
  output_truncated?: boolean;
  output_bytes_limit?: number;
  duration_ms: number;
  failure?: string;
};

export type WorkspaceFileEntry = {
  name: string;
  path: string;
  kind: string;
  size?: number;
  mod_time?: string;
};

export type WorkspaceFileStreamCancelParams = {
  stream_id: string;
};

export type WorkspaceFileStreamCancelResult = {
  stream_id: string;
  cancelled: boolean;
};

export type WorkspaceFileStreamFrame = {
  stream_id: string;
  request_id?: string;
  workspace_id: string;
  target: string;
  path: string;
  kind?: string;
  name?: string;
  mime_type?: string;
  size?: number;
  seq: number;
  offset: number;
  data_base64?: string;
  final?: boolean;
  error_code?: string;
  error_message?: string;
};

export type WorkspaceFileStreamResult = {
  stream_id: string;
  workspace_id: string;
  target: string;
  path: string;
  kind: string;
  name?: string;
  mime_type?: string;
  size?: number;
  offset: number;
  chunk_size: number;
};

export type WorkspaceFileTextEdit = {
  old_string: string;
  new_string: string;
  replace_all?: boolean;
};

export type WorkspaceFilesApplyPatchParams = {
  workspace_id: string;
  path: string;
  edits: WorkspaceFileTextEdit[];
};

export type WorkspaceFilesApplyPatchResult = {
  workspace_id: string;
  target: string;
  path: string;
  kind: string;
  size: number;
  applied_edits: number;
  structured_patch?: Record<string, unknown>[];
};

export type WorkspaceFilesDeleteParams = {
  workspace_id: string;
  path: string;
  recursive?: boolean;
  force?: boolean;
};

export type WorkspaceFilesDeleteResult = {
  workspace_id: string;
  target: string;
  path: string;
  kind: string;
  removed: boolean;
};

export type WorkspaceFilesMoveParams = {
  workspace_id: string;
  path: string;
  destination_path: string;
  overwrite?: boolean;
  create_parents?: boolean;
};

export type WorkspaceFilesMoveResult = {
  workspace_id: string;
  target: string;
  from_path: string;
  to_path: string;
  kind: string;
  size?: number;
};

export type WorkspaceFilesReadParams = {
  workspace_id: string;
  path: string;
  mode: string;
  max_bytes: number;
};

export type WorkspaceFilesReadResult = {
  workspace_id: string;
  target: string;
  path: string;
  kind: string;
  name?: string;
  size?: number;
  mod_time?: string;
  mime_type?: string;
  content_base64?: string;
  entries?: WorkspaceFileEntry[];
  truncated?: boolean;
};

export type WorkspaceFilesStreamParams = {
  workspace_id: string;
  path: string;
  offset?: number;
  chunk_size?: number;
};

export type WorkspaceFilesWriteParams = {
  workspace_id: string;
  path: string;
  content: string;
  content_base64: string;
  create_parents?: boolean;
};

export type WorkspaceFilesWriteResult = {
  workspace_id: string;
  target: string;
  path: string;
  kind: string;
  size: number;
};

export type WorkspaceReferenceParams = {
  workspace_id: string;
};

export type WorkspaceRemovedNormalized = {
  "id"?: unknown;
  "reason"?: unknown;
  "workspace_id"?: unknown;
  [key: string]: unknown;
};

export type WorkspaceTarget = "local" | "ssh";

export type ControlActionParamMap = {
  "attachment.ingest": AttachmentIngestParams;
  "attachment.ingest.chunk": AttachmentIngestChunkParams;
  "attachment.ingest.finish": AttachmentIngestFinishParams;
  "attachment.ingest.start": AttachmentIngestStartParams;
  "core.control.interrupt": SessionReferenceParams;
  "core.control.native_session.import": NativeSessionImportParams;
  "core.control.queue.cancel": QueueControlParams;
  "core.control.queue.steer": QueueControlParams;
  "core.control.session.create": CreateSessionRequest;
  "core.control.session.delete": SessionDeleteParams;
  "core.control.session.fork": SessionForkControlParams;
  "core.control.session_input": SessionInputControlParams;
  "core.control.workspace.connect": WorkspaceReferenceParams;
  "core.control.workspace.create": CreateWorkspaceRequest;
  "core.control.workspace.delete": WorkspaceReferenceParams;
  "core.control.workspace.disconnect": WorkspaceReferenceParams;
  "core.read.events": EventWindowParams;
  "core.read.host_snapshot": HostSnapshotRequest;
  "core.read.native_sessions": NativeSessionsReadParams;
  "core.read.ping": Record<string, never>;
  "core.read.session_view": SessionReferenceParams;
  "core.read.sessions": SessionsReadParams;
  "core.read.workbench": Record<string, never>;
  "core.read.workspace.connection": WorkspaceReferenceParams;
  "core.read.workspaces": Record<string, never>;
  "core.subscribe.events": EventSubscriptionParams;
  "core.unsubscribe.events": EventSubscriptionCancelParams;
  "host.fs.browse": HostFileSystemBrowseParams;
  "host.pairing.approve": PairingRequestResolveParams;
  "host.pairing.deny": PairingRequestResolveParams;
  "host.pairing.list": Record<string, never>;
  "host.trust.list": Record<string, never>;
  "host.trust.revoke": HostTrustRevokeParams;
  "interaction.respond": InteractionRespondParams;
  "media.download": MediaReadParams;
  "media.read": MediaReadParams;
  "media.stream": MediaStreamParams;
  "media.stream.cancel": MediaStreamCancelParams;
  "session.edit": SessionEditParams;
  "terminal.attach": TerminalAttachParams;
  "terminal.close": TerminalCloseParams;
  "terminal.detach": TerminalDetachParams;
  "terminal.heartbeat_ack": TerminalHeartbeatAckParams;
  "terminal.input": TerminalInputParams;
  "terminal.list": Record<string, never>;
  "terminal.open": TerminalOpenParams;
  "terminal.resize": TerminalResizeParams;
  "workspace.exec": WorkspaceExecParams;
  "workspace.files.apply_patch": WorkspaceFilesApplyPatchParams;
  "workspace.files.delete": WorkspaceFilesDeleteParams;
  "workspace.files.move": WorkspaceFilesMoveParams;
  "workspace.files.read": WorkspaceFilesReadParams;
  "workspace.files.stream": WorkspaceFilesStreamParams;
  "workspace.files.stream.cancel": WorkspaceFileStreamCancelParams;
  "workspace.files.write": WorkspaceFilesWriteParams;
};

export type ControlActionResultMap = {
  "attachment.ingest": AttachmentIngestResult;
  "attachment.ingest.chunk": AttachmentIngestChunkResult;
  "attachment.ingest.finish": AttachmentIngestFinishResult;
  "attachment.ingest.start": AttachmentIngestStartResult;
  "core.control.interrupt": OkResult;
  "core.control.native_session.import": NativeSessionImportResponse;
  "core.control.queue.cancel": QueueControlResult;
  "core.control.queue.steer": QueueControlResult;
  "core.control.session.create": Session;
  "core.control.session.delete": SessionDeleteResult;
  "core.control.session.fork": SessionForkResponse;
  "core.control.session_input": SessionInputResult;
  "core.control.workspace.connect": WorkspaceConnection;
  "core.control.workspace.create": Workspace;
  "core.control.workspace.delete": OkResult;
  "core.control.workspace.disconnect": WorkspaceConnection;
  "core.read.events": AstralEvent[];
  "core.read.host_snapshot": HostSnapshotResponse;
  "core.read.native_sessions": NativeSessionListResponse;
  "core.read.ping": OkResult;
  "core.read.session_view": SessionView;
  "core.read.sessions": Session[];
  "core.read.workbench": WorkbenchState;
  "core.read.workspace.connection": WorkspaceConnection;
  "core.read.workspaces": Workspace[];
  "core.subscribe.events": EventSubscriptionResult;
  "core.unsubscribe.events": EventSubscriptionCancelResult;
  "host.fs.browse": HostFileSystemBrowseResult;
  "host.pairing.approve": PairingRequestResolveResult;
  "host.pairing.deny": PairingRequestResolveResult;
  "host.pairing.list": PairingRequestListResult;
  "host.trust.list": HostTrustListResult;
  "host.trust.revoke": HostTrustRevokeResult;
  "interaction.respond": OkResult;
  "media.download": MediaReadResult;
  "media.read": MediaReadResult;
  "media.stream": MediaStreamResult;
  "media.stream.cancel": MediaStreamCancelResult;
  "session.edit": OkResult;
  "terminal.attach": TerminalAttachResult;
  "terminal.close": TerminalAckResult;
  "terminal.detach": TerminalAttachResult;
  "terminal.heartbeat_ack": TerminalAckResult;
  "terminal.input": TerminalAckResult;
  "terminal.list": TerminalTab[];
  "terminal.open": TerminalOpenResult;
  "terminal.resize": TerminalAckResult;
  "workspace.exec": WorkspaceExecResult;
  "workspace.files.apply_patch": WorkspaceFilesApplyPatchResult;
  "workspace.files.delete": WorkspaceFilesDeleteResult;
  "workspace.files.move": WorkspaceFilesMoveResult;
  "workspace.files.read": WorkspaceFilesReadResult;
  "workspace.files.stream": WorkspaceFileStreamResult;
  "workspace.files.stream.cancel": WorkspaceFileStreamCancelResult;
  "workspace.files.write": WorkspaceFilesWriteResult;
};

export type ControlActionParams<A extends ControlAction> = ControlActionParamMap[A];

export type ControlActionResult<A extends ControlAction> = ControlActionResultMap[A];

