package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	protocolmeta "github.com/oines/astralops/pkg/protocol"
)

type typeDecl struct {
	name string
	expr ast.Expr
}

type enumValue struct {
	name  string
	value string
}

type generator struct {
	types       []typeDecl
	stringEnums map[string][]enumValue
	actionSpecs []actionSpec
	eventFields map[string][]string
}

type actionSpec struct {
	action     string
	paramsType string
	resultType string
}

func main() {
	pkgDir := flag.String("pkg", "", "Go package directory to read")
	out := flag.String("out", "", "TypeScript output path")
	swiftOut := flag.String("swift-out", "", "Swift output path")
	flag.Parse()
	if *pkgDir == "" || *out == "" {
		fatalf("-pkg and -out are required")
	}
	gen, err := load(*pkgDir)
	if err != nil {
		fatalf("%v", err)
	}
	body, err := gen.emit()
	if err != nil {
		fatalf("%v", err)
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fatalf("%v", err)
	}
	if err := os.WriteFile(*out, body, 0o644); err != nil {
		fatalf("%v", err)
	}
	if *swiftOut != "" {
		swiftBody, err := gen.emitSwift()
		if err != nil {
			fatalf("%v", err)
		}
		if err := os.MkdirAll(filepath.Dir(*swiftOut), 0o755); err != nil {
			fatalf("%v", err)
		}
		if err := os.WriteFile(*swiftOut, swiftBody, 0o644); err != nil {
			fatalf("%v", err)
		}
	}
}

func load(pkgDir string) (*generator, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, pkgDir, func(info os.FileInfo) bool {
		return !strings.HasSuffix(info.Name(), "_test.go")
	}, 0)
	if err != nil {
		return nil, err
	}
	var pkg *ast.Package
	for _, value := range pkgs {
		pkg = value
		break
	}
	if pkg == nil {
		return nil, fmt.Errorf("no Go package found in %s", pkgDir)
	}
	gen := &generator{stringEnums: map[string][]enumValue{}}
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			switch genDecl.Tok {
			case token.TYPE:
				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok || !typeSpec.Name.IsExported() {
						continue
					}
					if typeSpec.Assign.IsValid() {
						if _, external := typeSpec.Type.(*ast.SelectorExpr); external {
							continue
						}
						gen.types = append(gen.types, typeDecl{name: typeSpec.Name.Name, expr: typeSpec.Type})
						continue
					}
					gen.types = append(gen.types, typeDecl{name: typeSpec.Name.Name, expr: typeSpec.Type})
				}
			case token.CONST:
				var blockType string
				for _, spec := range genDecl.Specs {
					valueSpec, ok := spec.(*ast.ValueSpec)
					if !ok {
						continue
					}
					if valueSpec.Type != nil {
						if typeName, ok := valueSpec.Type.(*ast.Ident); ok && typeName.IsExported() {
							blockType = typeName.Name
						} else {
							blockType = ""
						}
					}
					if blockType == "" || len(valueSpec.Values) == 0 {
						continue
					}
					for index, name := range valueSpec.Names {
						if !name.IsExported() || index >= len(valueSpec.Values) {
							continue
						}
						lit, ok := valueSpec.Values[index].(*ast.BasicLit)
						if !ok || lit.Kind != token.STRING {
							continue
						}
						value, err := strconv.Unquote(lit.Value)
						if err != nil {
							return nil, err
						}
						gen.stringEnums[blockType] = append(gen.stringEnums[blockType], enumValue{name: name.Name, value: value})
					}
				}
			case token.VAR:
				specs, err := parseControlActionSpecs(genDecl)
				if err != nil {
					return nil, err
				}
				gen.actionSpecs = append(gen.actionSpecs, specs...)
			}
		}
	}
	sort.Slice(gen.types, func(i, j int) bool { return gen.types[i].name < gen.types[j].name })
	for key := range gen.stringEnums {
		sort.Slice(gen.stringEnums[key], func(i, j int) bool {
			return gen.stringEnums[key][i].value < gen.stringEnums[key][j].value
		})
	}
	actionValues := enumNameValues(gen.stringEnums["ControlAction"])
	for index := range gen.actionSpecs {
		if value := actionValues[gen.actionSpecs[index].action]; value != "" {
			gen.actionSpecs[index].action = value
		}
	}
	sort.Slice(gen.actionSpecs, func(i, j int) bool { return gen.actionSpecs[i].action < gen.actionSpecs[j].action })
	gen.eventFields = loadEventFields()
	return gen, nil
}

func (g *generator) emit() ([]byte, error) {
	var out bytes.Buffer
	out.WriteString("// Code generated by tools/protocolgen. DO NOT EDIT.\n\n")
	for _, decl := range g.types {
		if decl.name == "AstralEvent" {
			g.emitTSAstralEvent(&out)
			continue
		}
		if decl.name == "AstralEventNormalized" {
			g.emitTSAstralEventNormalized(&out)
			continue
		}
		if strings.HasSuffix(decl.name, "Normalized") {
			g.emitTSAstralNormalizedType(&out, decl.name)
			continue
		}
		if values := g.stringEnums[decl.name]; len(values) > 0 {
			parts := make([]string, len(values))
			for index, enum := range values {
				parts[index] = strconv.Quote(enum.value)
			}
			fmt.Fprintf(&out, "export type %s = %s;\n\n", decl.name, strings.Join(parts, " | "))
			continue
		}
		ts, err := g.tsType(decl.expr)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", decl.name, err)
		}
		if fields, ok := ts.(structFields); ok {
			fmt.Fprintf(&out, "export type %s = {\n", decl.name)
			for _, field := range fields {
				optional := ""
				if field.optional {
					optional = "?"
				}
				fmt.Fprintf(&out, "  %s%s: %s;\n", field.name, optional, field.typ)
			}
			out.WriteString("};\n\n")
			continue
		}
		fmt.Fprintf(&out, "export type %s = %s;\n\n", decl.name, ts)
	}
	g.emitTSControlActionMaps(&out)
	return out.Bytes(), nil
}

func (g *generator) eventPayloads() []eventPayload {
	values := g.stringEnums["AstralEventKind"]
	out := make([]eventPayload, 0, len(values))
	for _, value := range values {
		if !strings.HasPrefix(value.name, "AstralEventKind") {
			continue
		}
		payload := strings.TrimPrefix(value.name, "AstralEventKind") + "Normalized"
		out = append(out, eventPayload{kind: value.value, typeName: payload, swiftCase: swiftIdentifier(strings.TrimPrefix(value.name, "AstralEventKind"))})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].kind < out[j].kind })
	return out
}

type eventPayload struct {
	kind      string
	typeName  string
	swiftCase string
}

func loadEventFields() map[string][]string {
	out := map[string][]string{}
	for kind, fields := range protocolmeta.AstralEventNormalizedFieldSpecs() {
		names := make([]string, 0, len(fields))
		seen := map[string]bool{}
		for _, field := range fields {
			if field.Name == "" || seen[field.Name] {
				continue
			}
			seen[field.Name] = true
			names = append(names, field.Name)
		}
		sort.Strings(names)
		out[string(kind)] = names
	}
	return out
}

func (g *generator) payloadFields(typeName string) []string {
	for _, payload := range g.eventPayloads() {
		if payload.typeName == typeName {
			return g.eventFields[payload.kind]
		}
	}
	return nil
}

func (g *generator) emitTSAstralNormalizedType(out *bytes.Buffer, typeName string) {
	fmt.Fprintf(out, "export type %s = {\n", typeName)
	for _, field := range g.payloadFields(typeName) {
		fmt.Fprintf(out, "  %s?: unknown;\n", tsPropertyName(field))
	}
	out.WriteString("  [key: string]: unknown;\n")
	out.WriteString("};\n\n")
}

func (g *generator) emitTSAstralEventNormalized(out *bytes.Buffer) {
	payloads := g.eventPayloads()
	parts := make([]string, 0, len(payloads))
	for _, payload := range payloads {
		parts = append(parts, payload.typeName)
	}
	if len(parts) == 0 {
		out.WriteString("export type AstralEventNormalized = { [key: string]: unknown };\n\n")
		return
	}
	fmt.Fprintf(out, "export type AstralEventNormalized = %s;\n\n", strings.Join(parts, " | "))
}

func (g *generator) emitTSAstralEvent(out *bytes.Buffer) {
	out.WriteString("export type AstralEventBase = {\n")
	out.WriteString("  seq: number;\n")
	out.WriteString("  ts: string;\n")
	out.WriteString("  workspace_id: string;\n")
	out.WriteString("  session_id: string;\n")
	out.WriteString("  agent: AgentKind;\n")
	out.WriteString("  raw?: unknown;\n")
	out.WriteString("};\n\n")
	out.WriteString("export type AstralEvent =\n")
	for _, payload := range g.eventPayloads() {
		fmt.Fprintf(out, "  | (AstralEventBase & { kind: %s; normalized: %s })\n", strconv.Quote(payload.kind), payload.typeName)
	}
	out.WriteString(";\n\n")
}

func (g *generator) emitTSControlActionMaps(out *bytes.Buffer) {
	if len(g.actionSpecs) == 0 {
		return
	}
	out.WriteString("export type ControlActionParamMap = {\n")
	for _, spec := range g.actionSpecs {
		fmt.Fprintf(out, "  %s: %s;\n", strconv.Quote(spec.action), tsSpecType(spec.paramsType, true))
	}
	out.WriteString("};\n\n")
	out.WriteString("export type ControlActionResultMap = {\n")
	for _, spec := range g.actionSpecs {
		fmt.Fprintf(out, "  %s: %s;\n", strconv.Quote(spec.action), tsSpecType(spec.resultType, false))
	}
	out.WriteString("};\n\n")
	out.WriteString("export type ControlActionParams<A extends ControlAction> = ControlActionParamMap[A];\n\n")
	out.WriteString("export type ControlActionResult<A extends ControlAction> = ControlActionResultMap[A];\n\n")
}

func (g *generator) emitSwift() ([]byte, error) {
	var out bytes.Buffer
	out.WriteString("// Code generated by tools/protocolgen. DO NOT EDIT.\n\n")
	out.WriteString("import Foundation\n\n")
	out.WriteString("enum GeneratedProtocol {\n")
	for _, decl := range g.types {
		if decl.name == "AstralEvent" {
			g.emitSwiftAstralEvent(&out)
			continue
		}
		if decl.name == "AstralEventNormalized" {
			continue
		}
		if strings.HasSuffix(decl.name, "Normalized") {
			g.emitSwiftAstralNormalizedStruct(&out, decl.name)
			continue
		}
		if values := g.stringEnums[decl.name]; len(values) > 0 {
			fmt.Fprintf(&out, "  enum %s: String, Codable, Equatable, Sendable {\n", decl.name)
			used := map[string]int{}
			for _, enum := range values {
				caseName := swiftCaseName(decl.name, enum.name, enum.value)
				if count := used[caseName]; count > 0 {
					used[caseName] = count + 1
					caseName = fmt.Sprintf("%s%d", caseName, count+1)
				} else {
					used[caseName] = 1
				}
				fmt.Fprintf(&out, "    case %s = %s\n", caseName, strconv.Quote(enum.value))
			}
			out.WriteString("  }\n\n")
			continue
		}
		fields, ok, err := g.swiftStructFields(decl.expr)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", decl.name, err)
		}
		if !ok {
			alias, err := g.swiftExpr(decl.expr)
			if err != nil {
				return nil, fmt.Errorf("%s: %w", decl.name, err)
			}
			fmt.Fprintf(&out, "  typealias %s = %s\n\n", decl.name, alias)
			continue
		}
		fmt.Fprintf(&out, "  struct %s: Codable, Equatable {\n", decl.name)
		for _, field := range fields {
			typ := field.typ
			if field.optional && !strings.HasSuffix(typ, "?") {
				typ += "?"
			}
			fmt.Fprintf(&out, "    var %s: %s\n", swiftIdentifier(field.name), typ)
		}
		if len(fields) > 0 {
			out.WriteString("\n")
			out.WriteString("    enum CodingKeys: String, CodingKey {\n")
			for _, field := range fields {
				swiftName := swiftIdentifier(field.name)
				if swiftName == field.name {
					fmt.Fprintf(&out, "      case %s\n", swiftName)
				} else {
					fmt.Fprintf(&out, "      case %s = %s\n", swiftName, strconv.Quote(field.name))
				}
			}
			out.WriteString("    }\n")
		}
		out.WriteString("  }\n\n")
	}
	g.emitSwiftAstralNormalizedPayload(&out)
	out.WriteString("}\n")
	return out.Bytes(), nil
}

func (g *generator) emitSwiftAstralNormalizedStruct(out *bytes.Buffer, typeName string) {
	fmt.Fprintf(out, "  struct %s: Codable, Equatable {\n", typeName)
	out.WriteString("    var storage: [String: JSONValue]\n\n")
	out.WriteString("    init(_ value: [String: JSONValue] = [:]) {\n")
	out.WriteString("      self.storage = value\n")
	out.WriteString("    }\n\n")
	out.WriteString("    init(from decoder: Decoder) throws {\n")
	out.WriteString("      storage = try [String: JSONValue](from: decoder)\n")
	out.WriteString("    }\n\n")
	out.WriteString("    func encode(to encoder: Encoder) throws {\n")
	out.WriteString("      try storage.encode(to: encoder)\n")
	out.WriteString("    }\n")
	for _, group := range swiftFieldGroups(g.payloadFields(typeName)) {
		out.WriteString("\n")
		fmt.Fprintf(out, "    var %s: JSONValue? { ", group.name)
		for index, field := range group.fields {
			if index > 0 {
				out.WriteString(" ?? ")
			}
			fmt.Fprintf(out, "storage[%s]", strconv.Quote(field))
		}
		out.WriteString(" }\n")
	}
	out.WriteString("  }\n\n")
}

func (g *generator) emitSwiftAstralEvent(out *bytes.Buffer) {
	out.WriteString("  struct AstralEvent: Codable, Equatable {\n")
	out.WriteString("    var seq: Int64\n")
	out.WriteString("    var ts: String\n")
	out.WriteString("    var workspaceId: String\n")
	out.WriteString("    var sessionId: String\n")
	out.WriteString("    var agent: AgentKind\n")
	out.WriteString("    var kind: AstralEventKind\n")
	out.WriteString("    var normalized: AstralNormalizedPayload\n")
	out.WriteString("    var raw: JSONValue?\n\n")
	out.WriteString("    enum CodingKeys: String, CodingKey {\n")
	out.WriteString("      case seq\n")
	out.WriteString("      case ts\n")
	out.WriteString("      case workspaceId = \"workspace_id\"\n")
	out.WriteString("      case sessionId = \"session_id\"\n")
	out.WriteString("      case agent\n")
	out.WriteString("      case kind\n")
	out.WriteString("      case normalized\n")
	out.WriteString("      case raw\n")
	out.WriteString("    }\n\n")
	out.WriteString("    init(from decoder: Decoder) throws {\n")
	out.WriteString("      let container = try decoder.container(keyedBy: CodingKeys.self)\n")
	out.WriteString("      seq = try container.decode(Int64.self, forKey: .seq)\n")
	out.WriteString("      ts = try container.decode(String.self, forKey: .ts)\n")
	out.WriteString("      workspaceId = try container.decode(String.self, forKey: .workspaceId)\n")
	out.WriteString("      sessionId = try container.decode(String.self, forKey: .sessionId)\n")
	out.WriteString("      agent = try container.decode(AgentKind.self, forKey: .agent)\n")
	out.WriteString("      kind = try container.decode(AstralEventKind.self, forKey: .kind)\n")
	out.WriteString("      normalized = try AstralNormalizedPayload.decode(kind: kind, from: container, forKey: .normalized)\n")
	out.WriteString("      raw = try container.decodeIfPresent(JSONValue.self, forKey: .raw)\n")
	out.WriteString("    }\n\n")
	out.WriteString("    func encode(to encoder: Encoder) throws {\n")
	out.WriteString("      var container = encoder.container(keyedBy: CodingKeys.self)\n")
	out.WriteString("      try container.encode(seq, forKey: .seq)\n")
	out.WriteString("      try container.encode(ts, forKey: .ts)\n")
	out.WriteString("      try container.encode(workspaceId, forKey: .workspaceId)\n")
	out.WriteString("      try container.encode(sessionId, forKey: .sessionId)\n")
	out.WriteString("      try container.encode(agent, forKey: .agent)\n")
	out.WriteString("      try container.encode(kind, forKey: .kind)\n")
	out.WriteString("      try container.encode(normalized, forKey: .normalized)\n")
	out.WriteString("      try container.encodeIfPresent(raw, forKey: .raw)\n")
	out.WriteString("    }\n")
	out.WriteString("  }\n\n")
}

func (g *generator) emitSwiftAstralNormalizedPayload(out *bytes.Buffer) {
	out.WriteString("  enum AstralNormalizedPayload: Codable, Equatable {\n")
	for _, payload := range g.eventPayloads() {
		fmt.Fprintf(out, "    case %s(%s)\n", payload.swiftCase, payload.typeName)
	}
	out.WriteString("\n")
	out.WriteString("    static func decode<K: CodingKey>(kind: AstralEventKind, from container: KeyedDecodingContainer<K>, forKey key: K) throws -> AstralNormalizedPayload {\n")
	out.WriteString("      switch kind {\n")
	for _, payload := range g.eventPayloads() {
		fmt.Fprintf(out, "      case .%s:\n", swiftCaseName("AstralEventKind", "AstralEventKind"+strings.TrimSuffix(payload.typeName, "Normalized"), payload.kind))
		fmt.Fprintf(out, "        return .%s(try container.decode(%s.self, forKey: key))\n", payload.swiftCase, payload.typeName)
	}
	out.WriteString("      }\n")
	out.WriteString("    }\n\n")
	out.WriteString("    init(from decoder: Decoder) throws {\n")
	out.WriteString("      let value = try JSONValue(from: decoder)\n")
	out.WriteString("      self = .controlRaw(ControlRawNormalized([\"value\": value]))\n")
	out.WriteString("    }\n\n")
	out.WriteString("    func encode(to encoder: Encoder) throws {\n")
	out.WriteString("      switch self {\n")
	for _, payload := range g.eventPayloads() {
		fmt.Fprintf(out, "      case .%s(let value): try value.encode(to: encoder)\n", payload.swiftCase)
	}
	out.WriteString("      }\n")
	out.WriteString("    }\n")
	out.WriteString("  }\n\n")
}

func (g *generator) swiftStructFields(expr ast.Expr) ([]structField, bool, error) {
	value, ok := expr.(*ast.StructType)
	if !ok {
		return nil, false, nil
	}
	fields := []structField{}
	for _, field := range value.Fields.List {
		if len(field.Names) == 0 {
			continue
		}
		jsonName, omitempty, skip := jsonField(field)
		if skip {
			continue
		}
		fieldType, err := g.swiftExpr(field.Type)
		if err != nil {
			return nil, false, err
		}
		for _, name := range field.Names {
			if !name.IsExported() {
				continue
			}
			outName := jsonName
			if outName == "" {
				outName = lowerFirst(name.Name)
			}
			fields = append(fields, structField{name: outName, typ: fieldType, optional: omitempty || isPointer(field.Type)})
		}
	}
	return fields, true, nil
}

func parseControlActionSpecs(decl *ast.GenDecl) ([]actionSpec, error) {
	specs := []actionSpec{}
	for _, spec := range decl.Specs {
		valueSpec, ok := spec.(*ast.ValueSpec)
		if !ok {
			continue
		}
		for index, name := range valueSpec.Names {
			if name.Name != "controlActionSpecs" || index >= len(valueSpec.Values) {
				continue
			}
			lit, ok := valueSpec.Values[index].(*ast.CompositeLit)
			if !ok {
				continue
			}
			for _, elt := range lit.Elts {
				kv, ok := elt.(*ast.KeyValueExpr)
				if !ok {
					continue
				}
				call, ok := kv.Value.(*ast.CallExpr)
				if !ok || len(call.Args) != 4 {
					continue
				}
				fun, ok := call.Fun.(*ast.Ident)
				if !ok || fun.Name != "spec" {
					continue
				}
				action := identName(call.Args[0])
				paramsType, err := stringLiteral(call.Args[2])
				if err != nil {
					return nil, err
				}
				resultType, err := stringLiteral(call.Args[3])
				if err != nil {
					return nil, err
				}
				specs = append(specs, actionSpec{action: action, paramsType: paramsType, resultType: resultType})
			}
		}
	}
	return specs, nil
}

func identName(expr ast.Expr) string {
	if ident, ok := expr.(*ast.Ident); ok {
		return ident.Name
	}
	return ""
}

func stringLiteral(expr ast.Expr) (string, error) {
	lit, ok := expr.(*ast.BasicLit)
	if !ok || lit.Kind != token.STRING {
		return "", nil
	}
	return strconv.Unquote(lit.Value)
}

func enumNameValues(values []enumValue) map[string]string {
	out := map[string]string{}
	for _, value := range values {
		out[value.name] = value.value
	}
	return out
}

func tsSpecType(value string, params bool) string {
	if value == "" {
		if params {
			return "Record<string, never>"
		}
		return "unknown"
	}
	if strings.HasSuffix(value, "[]") {
		return strings.TrimSuffix(value, "[]") + "[]"
	}
	return value
}

func (g *generator) swiftExpr(expr ast.Expr) (string, error) {
	switch value := expr.(type) {
	case *ast.Ident:
		if len(g.stringEnums[value.Name]) > 0 {
			return value.Name, nil
		}
		switch value.Name {
		case "string":
			return "String", nil
		case "bool":
			return "Bool", nil
		case "int", "int8", "int16", "int32", "uint", "uint8", "uint16", "uint32":
			return "Int", nil
		case "int64", "uint64":
			return "Int64", nil
		case "float32", "float64":
			return "Double", nil
		case "any":
			return "JSONValue", nil
		default:
			return value.Name, nil
		}
	case *ast.InterfaceType:
		return "JSONValue", nil
	case *ast.StarExpr:
		return g.swiftExpr(value.X)
	case *ast.ArrayType:
		inner, err := g.swiftExpr(value.Elt)
		if err != nil {
			return "", err
		}
		return "[" + inner + "]", nil
	case *ast.MapType:
		key, ok := value.Key.(*ast.Ident)
		if !ok || key.Name != "string" {
			return "[String: JSONValue]", nil
		}
		inner, err := g.swiftExpr(value.Value)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("[String: %s]", inner), nil
	case *ast.SelectorExpr:
		if value.Sel.Name == "RawMessage" {
			return "JSONValue", nil
		}
		return value.Sel.Name, nil
	default:
		return "JSONValue", nil
	}
}

type structField struct {
	name     string
	typ      string
	optional bool
}

type structFields []structField

func (s structFields) String() string {
	return "Record<string, unknown>"
}

func (g *generator) tsType(expr ast.Expr) (fmt.Stringer, error) {
	switch value := expr.(type) {
	case *ast.StructType:
		fields := structFields{}
		for _, field := range value.Fields.List {
			if len(field.Names) == 0 {
				continue
			}
			jsonName, omitempty, skip := jsonField(field)
			if skip {
				continue
			}
			fieldType, err := g.tsExpr(field.Type)
			if err != nil {
				return nil, err
			}
			for _, name := range field.Names {
				if !name.IsExported() {
					continue
				}
				outName := jsonName
				if outName == "" {
					outName = lowerFirst(name.Name)
				}
				fields = append(fields, structField{
					name:     outName,
					typ:      fieldType,
					optional: omitempty || isPointer(field.Type),
				})
			}
		}
		return fields, nil
	default:
		ts, err := g.tsExpr(expr)
		return stringer(ts), err
	}
}

func (g *generator) tsExpr(expr ast.Expr) (string, error) {
	switch value := expr.(type) {
	case *ast.Ident:
		if values := g.stringEnums[value.Name]; len(values) > 0 {
			parts := make([]string, len(values))
			for index, enum := range values {
				parts[index] = strconv.Quote(enum.value)
			}
			return strings.Join(parts, " | "), nil
		}
		switch value.Name {
		case "string":
			return "string", nil
		case "bool":
			return "boolean", nil
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64":
			return "number", nil
		case "any":
			return "unknown", nil
		default:
			return value.Name, nil
		}
	case *ast.InterfaceType:
		return "unknown", nil
	case *ast.StarExpr:
		return g.tsExpr(value.X)
	case *ast.ArrayType:
		inner, err := g.tsExpr(value.Elt)
		if err != nil {
			return "", err
		}
		return inner + "[]", nil
	case *ast.MapType:
		key, ok := value.Key.(*ast.Ident)
		if !ok || key.Name != "string" {
			return "Record<string, unknown>", nil
		}
		inner, err := g.tsExpr(value.Value)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("Record<string, %s>", inner), nil
	case *ast.SelectorExpr:
		if value.Sel.Name == "RawMessage" {
			return "Record<string, unknown>", nil
		}
		return value.Sel.Name, nil
	default:
		return "unknown", nil
	}
}

func jsonField(field *ast.Field) (string, bool, bool) {
	if field.Tag == nil {
		return "", false, false
	}
	tag, err := strconv.Unquote(field.Tag.Value)
	if err != nil {
		return "", false, false
	}
	jsonTag := reflectTag(tag, "json")
	if jsonTag == "-" {
		return "", false, true
	}
	if jsonTag == "" {
		return "", false, false
	}
	parts := strings.Split(jsonTag, ",")
	name := parts[0]
	omitempty := false
	for _, part := range parts[1:] {
		if part == "omitempty" {
			omitempty = true
		}
	}
	return name, omitempty, false
}

func reflectTag(tag, key string) string {
	for tag != "" {
		tag = strings.TrimLeft(tag, " ")
		if tag == "" {
			break
		}
		i := strings.Index(tag, ":")
		if i < 0 {
			break
		}
		name := tag[:i]
		tag = tag[i+1:]
		if !strings.HasPrefix(tag, "\"") {
			break
		}
		value, rest, ok := scanQuoted(tag)
		if !ok {
			break
		}
		if name == key {
			return value
		}
		tag = rest
	}
	return ""
}

func scanQuoted(value string) (string, string, bool) {
	for i := 1; i < len(value); i++ {
		if value[i] == '\\' {
			i++
			continue
		}
		if value[i] == '"' {
			unquoted, err := strconv.Unquote(value[:i+1])
			if err != nil {
				return "", "", false
			}
			return unquoted, value[i+1:], true
		}
	}
	return "", "", false
}

func isPointer(expr ast.Expr) bool {
	_, ok := expr.(*ast.StarExpr)
	return ok
}

func lowerFirst(value string) string {
	if value == "" {
		return ""
	}
	return strings.ToLower(value[:1]) + value[1:]
}

func tsPropertyName(value string) string {
	return strconv.Quote(value)
}

type swiftFieldGroup struct {
	name   string
	fields []string
}

func swiftFieldGroups(fields []string) []swiftFieldGroup {
	byName := map[string][]string{}
	order := []string{}
	for _, field := range fields {
		name := swiftIdentifier(field)
		if _, ok := byName[name]; !ok {
			order = append(order, name)
		}
		byName[name] = append(byName[name], field)
	}
	sort.Strings(order)
	out := make([]swiftFieldGroup, 0, len(order))
	for _, name := range order {
		out = append(out, swiftFieldGroup{name: name, fields: byName[name]})
	}
	return out
}

func swiftCaseName(typeName, constName, value string) string {
	name := constName
	if strings.HasPrefix(name, typeName) {
		name = strings.TrimPrefix(name, typeName)
	}
	if name == "" {
		name = value
	}
	name = lowerFirst(name)
	return swiftIdentifier(name)
}

func swiftIdentifier(value string) string {
	parts := []string{}
	var current strings.Builder
	for _, r := range value {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			current.WriteRune(r)
			continue
		}
		if current.Len() > 0 {
			parts = append(parts, current.String())
			current.Reset()
		}
	}
	if current.Len() > 0 {
		parts = append(parts, current.String())
	}
	if len(parts) == 0 {
		return "value"
	}
	out := strings.ToLower(parts[0][:1]) + parts[0][1:]
	for _, part := range parts[1:] {
		out += strings.ToUpper(part[:1]) + part[1:]
	}
	if out[0] >= '0' && out[0] <= '9' {
		out = "value" + strings.ToUpper(out[:1]) + out[1:]
	}
	switch out {
	case "class", "struct", "enum", "protocol", "extension", "func", "let", "var", "case", "default", "import", "public", "private", "internal", "switch":
		return "`" + out + "`"
	default:
		return out
	}
}

type stringer string

func (s stringer) String() string {
	return string(s)
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
