package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type typeDecl struct {
	name string
	expr ast.Expr
}

type generator struct {
	types       []typeDecl
	stringEnums map[string][]string
}

func main() {
	pkgDir := flag.String("pkg", "", "Go package directory to read")
	out := flag.String("out", "", "TypeScript output path")
	flag.Parse()
	if *pkgDir == "" || *out == "" {
		fatalf("-pkg and -out are required")
	}
	gen, err := load(*pkgDir)
	if err != nil {
		fatalf("%v", err)
	}
	body, err := gen.emit()
	if err != nil {
		fatalf("%v", err)
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fatalf("%v", err)
	}
	if err := os.WriteFile(*out, body, 0o644); err != nil {
		fatalf("%v", err)
	}
}

func load(pkgDir string) (*generator, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, pkgDir, func(info os.FileInfo) bool {
		return !strings.HasSuffix(info.Name(), "_test.go")
	}, 0)
	if err != nil {
		return nil, err
	}
	var pkg *ast.Package
	for _, value := range pkgs {
		pkg = value
		break
	}
	if pkg == nil {
		return nil, fmt.Errorf("no Go package found in %s", pkgDir)
	}
	gen := &generator{stringEnums: map[string][]string{}}
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			switch genDecl.Tok {
			case token.TYPE:
				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok || !typeSpec.Name.IsExported() {
						continue
					}
					if typeSpec.Assign.IsValid() {
						if _, external := typeSpec.Type.(*ast.SelectorExpr); external {
							continue
						}
						gen.types = append(gen.types, typeDecl{name: typeSpec.Name.Name, expr: typeSpec.Type})
						continue
					}
					gen.types = append(gen.types, typeDecl{name: typeSpec.Name.Name, expr: typeSpec.Type})
				}
			case token.CONST:
				for _, spec := range genDecl.Specs {
					valueSpec, ok := spec.(*ast.ValueSpec)
					if !ok || valueSpec.Type == nil || len(valueSpec.Values) == 0 {
						continue
					}
					typeName, ok := valueSpec.Type.(*ast.Ident)
					if !ok || !typeName.IsExported() {
						continue
					}
					for index, name := range valueSpec.Names {
						if !name.IsExported() || index >= len(valueSpec.Values) {
							continue
						}
						lit, ok := valueSpec.Values[index].(*ast.BasicLit)
						if !ok || lit.Kind != token.STRING {
							continue
						}
						value, err := strconv.Unquote(lit.Value)
						if err != nil {
							return nil, err
						}
						gen.stringEnums[typeName.Name] = append(gen.stringEnums[typeName.Name], value)
					}
				}
			}
		}
	}
	sort.Slice(gen.types, func(i, j int) bool { return gen.types[i].name < gen.types[j].name })
	for key := range gen.stringEnums {
		sort.Strings(gen.stringEnums[key])
	}
	return gen, nil
}

func (g *generator) emit() ([]byte, error) {
	var out bytes.Buffer
	out.WriteString("// Code generated by tools/protocolgen. DO NOT EDIT.\n\n")
	for _, decl := range g.types {
		if values := g.stringEnums[decl.name]; len(values) > 0 {
			parts := make([]string, len(values))
			for index, enum := range values {
				parts[index] = strconv.Quote(enum)
			}
			fmt.Fprintf(&out, "export type %s = %s;\n\n", decl.name, strings.Join(parts, " | "))
			continue
		}
		ts, err := g.tsType(decl.expr)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", decl.name, err)
		}
		if fields, ok := ts.(structFields); ok {
			fmt.Fprintf(&out, "export type %s = {\n", decl.name)
			for _, field := range fields {
				optional := ""
				if field.optional {
					optional = "?"
				}
				fmt.Fprintf(&out, "  %s%s: %s;\n", field.name, optional, field.typ)
			}
			out.WriteString("};\n\n")
			continue
		}
		fmt.Fprintf(&out, "export type %s = %s;\n\n", decl.name, ts)
	}
	return out.Bytes(), nil
}

type structField struct {
	name     string
	typ      string
	optional bool
}

type structFields []structField

func (s structFields) String() string {
	return "Record<string, unknown>"
}

func (g *generator) tsType(expr ast.Expr) (fmt.Stringer, error) {
	switch value := expr.(type) {
	case *ast.StructType:
		fields := structFields{}
		for _, field := range value.Fields.List {
			if len(field.Names) == 0 {
				continue
			}
			jsonName, omitempty, skip := jsonField(field)
			if skip {
				continue
			}
			fieldType, err := g.tsExpr(field.Type)
			if err != nil {
				return nil, err
			}
			for _, name := range field.Names {
				if !name.IsExported() {
					continue
				}
				outName := jsonName
				if outName == "" {
					outName = lowerFirst(name.Name)
				}
				fields = append(fields, structField{
					name:     outName,
					typ:      fieldType,
					optional: omitempty || isPointer(field.Type),
				})
			}
		}
		return fields, nil
	default:
		ts, err := g.tsExpr(expr)
		return stringer(ts), err
	}
}

func (g *generator) tsExpr(expr ast.Expr) (string, error) {
	switch value := expr.(type) {
	case *ast.Ident:
		if values := g.stringEnums[value.Name]; len(values) > 0 {
			parts := make([]string, len(values))
			for index, enum := range values {
				parts[index] = strconv.Quote(enum)
			}
			return strings.Join(parts, " | "), nil
		}
		switch value.Name {
		case "string":
			return "string", nil
		case "bool":
			return "boolean", nil
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64":
			return "number", nil
		case "any":
			return "unknown", nil
		default:
			return value.Name, nil
		}
	case *ast.InterfaceType:
		return "unknown", nil
	case *ast.StarExpr:
		return g.tsExpr(value.X)
	case *ast.ArrayType:
		inner, err := g.tsExpr(value.Elt)
		if err != nil {
			return "", err
		}
		return inner + "[]", nil
	case *ast.MapType:
		key, ok := value.Key.(*ast.Ident)
		if !ok || key.Name != "string" {
			return "Record<string, unknown>", nil
		}
		inner, err := g.tsExpr(value.Value)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("Record<string, %s>", inner), nil
	case *ast.SelectorExpr:
		return value.Sel.Name, nil
	default:
		return "unknown", nil
	}
}

func jsonField(field *ast.Field) (string, bool, bool) {
	if field.Tag == nil {
		return "", false, false
	}
	tag, err := strconv.Unquote(field.Tag.Value)
	if err != nil {
		return "", false, false
	}
	jsonTag := reflectTag(tag, "json")
	if jsonTag == "-" {
		return "", false, true
	}
	if jsonTag == "" {
		return "", false, false
	}
	parts := strings.Split(jsonTag, ",")
	name := parts[0]
	omitempty := false
	for _, part := range parts[1:] {
		if part == "omitempty" {
			omitempty = true
		}
	}
	return name, omitempty, false
}

func reflectTag(tag, key string) string {
	for tag != "" {
		tag = strings.TrimLeft(tag, " ")
		if tag == "" {
			break
		}
		i := strings.Index(tag, ":")
		if i < 0 {
			break
		}
		name := tag[:i]
		tag = tag[i+1:]
		if !strings.HasPrefix(tag, "\"") {
			break
		}
		value, rest, ok := scanQuoted(tag)
		if !ok {
			break
		}
		if name == key {
			return value
		}
		tag = rest
	}
	return ""
}

func scanQuoted(value string) (string, string, bool) {
	for i := 1; i < len(value); i++ {
		if value[i] == '\\' {
			i++
			continue
		}
		if value[i] == '"' {
			unquoted, err := strconv.Unquote(value[:i+1])
			if err != nil {
				return "", "", false
			}
			return unquoted, value[i+1:], true
		}
	}
	return "", "", false
}

func isPointer(expr ast.Expr) bool {
	_, ok := expr.(*ast.StarExpr)
	return ok
}

func lowerFirst(value string) string {
	if value == "" {
		return ""
	}
	return strings.ToLower(value[:1]) + value[1:]
}

type stringer string

func (s stringer) String() string {
	return string(s)
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
